#!/bin/bash
#
# [Ansible Role]
#
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Modified: Admin9705 & Deiteq & FlickerRate
# URL:      https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
# [Original Author Information]
# GitHub: https://github.com/Cloudbox/Cloudbox/tree/app/traktarr
# Author: l3uddz
# Donate: Paypal - l3uddz@gmail.com
#################################################################################
---
- name: Check service exists
  stat:
    path: "/etc/systemd/system/traktarr.service"
  register: traktarr_service

- name: Stop existing traktarr service
  systemd: state=stopped name=traktarr
  when: traktarr_service.stat.exists

- name: Create traktarr directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}} recurse=true"
  with_items:
    - /opt/traktarr
    
- name: Clone traktarr
  git:
    repo: https://github.com/Admin9705/traktarr
    dest: /opt/appdata/traktarr
    version: master
    force: yes
    
- name: Install pip requirements
  pip:
    requirements: /opt/traktarr/requirements.txt
    executable: pip3

- name: Check config exists
  stat:
    path: "/opt/appdata/traktarr/config.json"
  register: traktarr_config

- name: Import default config
  template:
    src: config.json.js2
    dest: /opt/appdata/traktarr/config.json
    force: yes
  when: traktarr_config.stat.exists == False

- name: Set traktarr.py as executable
  file:
    path: /opt/traktarr/traktarr.py
    mode: a+x

- name: Set directory permissions
  file: "path=/opt/traktarr state=directory owner=1000 group=1000 recurse=yes"

- name: "Create /usr/local/bin symlink"
  file:
    src: "/opt/appdata/traktarr/traktarr.py"
    dest: "/usr/local/bin/traktarr"
    state: link

- name: Import traktarr service
  template:
    src: traktarr.service.js2
    dest: /etc/systemd/system/traktarr.service 
    force: yes
  when: traktarr_service.stat.exists == False

- name: Load service file
  systemd: state=stopped name=traktarr daemon_reload=yes enabled=no
