#!/bin/bash
#
# [Ansible Role]
#
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   Admin9705 & Deiteq & FlickerRate
# URL:      https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
---
- include_role:
    name: variables

- name: Remove airsonic Container
  docker_container:
    name: airsonic
    state: absent

- name: Deploy airsonic Container
  docker_container:
    name: airsonic
    image: airsonic/airsonic
    pull: yes
    cpu_shares: 512
    published_ports:
      - "{{ports.stdout}}4040:4040"
    env:
      PUID: "1000"
      PGID: "1000"
    volumes:
      - /opt/appdata/airsonic:/airsonic/data
      - /mnt/unionfs/music:/airsonic/music
      - /opt/appdata/airsonic/playlists:/airsonic/playlists
      - /opt/appdata/airsonic/podcasts:/airsonic/podcasts
      - /etc/localtime:/etc/localtime:ro
    networks:
      - name: plexguide
        aliases:
          - airsonic
    labels:
      traefik.enable: "true"
      traefik.frontend.auth.basic: "{{auth.stdout}}"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:airsonic.{{domain.stdout}}"
      traefik.port: "4040"
    restart_policy: always
    state: started
