#!/bin/bash
#
# [Ansible Role]
#
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   Admin9705 & Deiteq
# URL:      https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
---
- include_role:
    name: variables

- name: Remove Sonarr Container
  docker_container:
    name: sonarr
    state: absent

- name: Deploy Sonarr Container
  docker_container:
    name: sonarr
    image: aront/sonarr
    pull: yes
    cpu_shares: 256
    published_ports:
      - "{{ports.stdout}}8989:8989"
    env:
      PUID: "1000"
      PGID: "1000"
    networks:
      - name: plexguide
        aliases:
          - sonarr
    volumes:
      - /opt/appdata/sonarr:/config
      - /opt/appdata/sonarr/mp4_automator:/config_mp4_automator
      - /mnt/unionfs:/unionfs
      - "{{path.stdout}}/sab/complete:/complete"
      - "{{path.stdout}}/nzbget/completed:/completed"
      - "{{path.stdout}}/deluge/downloaded:/downloaded"
      - "{{path.stdout}}/torrentvpn/downloaded:/data/completed"
      - "{{path.stdout}}/rutorrents:/downloads"
      - /etc/localtime:/etc/localtime:ro
    restart_policy: always
    state: started
    labels:
      traefik.enable: "true"
      traefik.frontend.auth.basic: "{{auth.stdout}}"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:sonarr.{{domain.stdout}}"
      traefik.port: "8989"
- name: Install autoProcess.ini
  template:
    src: autoProcess.ini
    dest: /opt/appdata/sonarr/mp4_automator/autoProcess.ini
    force: yes
    mode: 0775
