#!/bin/bash
#
# [Ansible Role]
#
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   Admin9705 & Deiteq & FlickerRate
# URL:      https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
---
- name: Register Domain
  shell: "cat /var/plexguide/server.domain"
  register: domain
  ignore_errors: True

- name: Register IP
  shell: "cat /var/plexguide/server.ip"
  register: ipaddress
  ignore_errors: True

- name: Register Ports
  shell: "cat /var/plexguide/server.ports"
  register: ports
  ignore_errors: True

- name: Register HD Path
  shell: "cat /var/plexguide/server.hd.path"
  register: path
  ignore_errors: True

- name: Register Auth Path
  shell: "cat /var/plexguide/server.ht"
  register: auth
  ignore_errors: True

- name: Logging Ansible Role Information
  shell: "echo 'INFO - Ansible Role {{pgrole}} Started' > /var/plexguide/pg.log && bash /opt/plexguide/roles/log/log.sh"

- name: Remove {{pgrole}} Container
  docker_container:
    name: "{{pgrole}}"
    state: absent
  ignore_errors: True

- name: Storing Role Name
  shell: "echo '{{pgrole}}' > /tmp/program_var"
  ignore_errors: True

- name: "Check New BreadCrumb"
  stat:
    path: "/var/plexguide/breadcrumb.{{pgrole}}"
  register: "breadcrumbs"

- name: Volume Recall
  include_role:
    name: pgmstart
    tasks_from: "{{pgrole}}.yml"
  ignore_errors: True
  when: "breadcrumbs.stat.exists == True"

  ### programs to update
  # bazarr
