---

- name: Remove Emby Container
  docker_container:
    name: emby
    state: absent

- name: Deploy Emby Container
  docker_container:
    name: emby
    image: emby/embyserver_netcore:latest
    pull: yes
    cpu_shares: 1024
    published_ports:
      - "8096:8096"
    env:
      PUID: "1000"
      PGID: "1000"
      HTTPS_METHOD: noredirect
    expose:
      - 8096 
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/appdata/embyserver:/config
      - /mnt/plexdrive4/:/plexdrive4
      - /mnt/unionfs:/unionfs
      - /mnt/encrypt:/encrypt
    networks:
      - name: plexguide
        aliases:
          - emby
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:emby.{{domain}}"
      traefik.port: "8096"
    restart_policy: always
    state: started
