---
- name: Remove Jackett Container
  docker_container:
    name: jackett
    state: absent

- name: Deploy Jacket Container
  docker_container:
    name: jackett
    image: linuxserver/jackett
    pull: yes
    cpu_shares: 256
    published_ports:
      - "{{ports}}9117:9117"
    env:
      PUID: "1000"
      PGID: "1000"
      HTTPS_METHOD: noredirect
    volumes:
      - /opt/appdata/jackett:/config
      - /mnt/deluge/temp:/temp
      - /mnt/deluge/downloaded:/downloaded
      - /mnt/deluge/torrent:/torrent
      - /mnt/unionfs:/unionfs
      - /etc/localtime:/etc/localtime:ro
    networks:
      - name: plexguide
        aliases:
          - jackett
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:jackett.{{domain}}"
      traefik.port: "9117"
    restart_policy: always
    state: started
