
---

- name: Register if Ports Are Closed
  stat:
    path: /opt/appdata/plexguide/ports-no
  register: ports_closed

- replace:
    path: /opt/appdata/plexguide/var.yml
    regexp: "ports:$"
    replace: 'ports: "127.0.0.1:"'
  when: ports_closed.stat.exists == True
  ignore_errors: yes

- replace:
    path: /opt/appdata/plexguide/var.yml
    regexp: '"ports: 127.0.0.1: 127.0.0.1:"$'
    replace: '"ports: 127.0.0.1:"'
  when: ports_closed.stat.exists == True

- replace:
    path: /opt/appdata/plexguide/var.yml
    regexp: '"ports: 127.0.0.1:"'
    replace: "ports:"
  when: ports_closed.stat.exists == False
  ignore_errors: yes

