---

- name: Remove Netdata Container
  docker_container:
    name: netdata
    state: absent

- name: Deploy NetData Container
  docker_container:
    name: netdata
    image: "titpetric/netdata:latest"
    pull: yes
    cpu_shares: 256
    published_ports:
      - "19999:19999"
    volumes:
      - "/sys:/host/sys:ro"
      - "/proc:/host/proc:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    env:
      PUID: 1000
      PGID: 1000
    networks:
      - name: plexguide
        aliases:
          - netdata
    restart_policy: always
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:netdata.{{domain}}"
      traefik.port: "19999"
      traefik.backend: "netdata"
