---
- name: Container
  docker_container:
    name: netdata
    image: "titpetric/netdata:latest"
    pull: yes
    published_ports:
      - "19999:19999"
    volumes:
      - "/sys:/host/sys:ro"
      - "/proc:/host/proc:ro"
    env:
      VIRTUAL_HOST: "netdata.*"
      VIRTUAL_PORT: 19999
      PUID: 1000
      PGID: 1000
    restart_policy: always
    state: started