---
language: bash
sudo: true
dist: xenial

#services: docker
# Doc: https://docs.travis-ci.com/user/customizing-the-build#Build-Matrix
#env:
#  - ANSIBLE_VERSION=latest

branches:
  only:
    - Edge

script:
- sudo bash ${PWD}/roles/baseline/scripts/ansible.sh
- sudo mkdir /var/plexguide/
- sudo bash ${PWD}/roles/baseline/scripts/gen.sh
- sudo bash ${PWD}/roles/baseline/scripts/folders.sh
- sudo ansible-playbook /${PWD}/opt/plexguide/pg.yml --tags rcloneinstall

#install:
#  # Install Ansible.
#  - sudo apt-get remove ansible
#  - sudo apt-add-repository --remove ppa:ansible/ansible -y && sudo add-apt-repository ppa:ansible/ansible-2.5 -y && sudo apt install ansible -y
#  - sudo apt-get update -y
#  - sudo apt-get install ansible 2.5.5 -y
#  - sudo apt-mark hold ansible
#  - sudo apt-get update -y

#script:
  # Check the role/playbook's syntax.
  #  - sudo pwd
  #- mv /home/travis/build/Admin9705/PlexGuide.com-The-Awesome-Plex-Server/* /opt/plexguide/
  #- sudo bash /opt/plexguide/roles/baseline/scripts/gen.sh
  #- sudo ansible-playbook -i /opt/plexguide/pg.yml --tags couchpotato --syntax-check

### Sources
# https://tasdikrahman.me/2017/04/06/Testing-your-ansible-roles-using-travis-CI/
