---
image: ubuntu

install:
  - sh: sudo mkdir -p /opt/plexguide
  - sh: sudo mkdir -p /var/plexguide
  - sh: sudo mkdir -p /opt/appdata/plexguide
  - sh: sudo mv /home/appveyor/projects/plexguide-com-the-awesome-plex-server/* /opt/plexguide/

  ###### EXECUTE SET VARIABLES
  - sh: sudo bash /opt/plexguide/rmenu/appveyor/var.sh

  ###### ANSIBLE INSTALL
  - sh: sudo bash /opt/plexguide/menu/alias/templates/plexguide

  ###### Install Containers - ABC Order

  ## new format checked (check NETDATA)
  - sh: sudo bash /opt/plexguide/roles/appveyor/containers.sh
 
  #### OUTPUTS
  - sh: sudo ansible --version | head -n1
  - sh: sudo rclone --version | head -n1
  - sh: sudo docker --version | head -n1
  - sh: sudo docker ps --format '{{.Names}}'

matrix:
  fast_finish: true

build: off
