---
- name: Removing Old NGINX File Directory
  file:
    state: absent
    path: /opt/appdata/traefik/traefik.toml

- name: Remove NGINX Container
  docker_container:
    name: nginx-proxy
    state: absent

- name: Remove LetsEncrypt
  docker_container:
    name: letsencrypt
    state: absent

- name: Removing Prior Traefik.toml
  file:
    state: absent
    path: /opt/appdata/traefik/traefik.toml

- name: Create Basic Directories
  file: "path={{item}} state=directory mode=0775 owner=1000 group=1000"
  with_items:
    - /opt/appdata/traefik

########## Move Script if not Present
- name: Check SCRIPT
  stat:
    path: "/opt/appdata/traefik/traefik.toml"
  register: script

- name: Installing Traefik.Toml
  template:
    src: traefik.toml
    dest: /opt/appdata/traefik/traefik.toml
    force: yes
  when: script.stat.exists == False

- name: Replace yourdomain.com with user input
  replace:
    path: /opt/appdata/traefik/traefik.toml
    regexp: yourdomain.com
    replace: "ffplex.com"

- name: Replace your@email.com with user input
  replace:
    path: /opt/appdata/traefik/traefik.toml
    regexp: user@gmail.com
    replace: "trash@trash.com"

#############################

- name: Remove Traefik
  docker_container:
    name: traefik
    state: absent

- name: Deploy Traefik
  docker_container:
    name: traefik
    image: traefik
    pull: yes
    cpu_shares: 256
    published_ports:
      - "8080:8080"
      - "80:80"
      - "443:443"
    env:
      VIRTUAL_HOST: "traefik.ffplex.com"
      VIRTUAL_PORT: 8080
    labels:
      traefik.docker.network: "dockerplatform_default"
      traefik.port: "8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - /opt/appdata/traefik/traefik.toml:/etc/traefik/traefik.toml
    restart_policy: always
    state: started
