---
version: '2'
services:
 plex:
   image: plexinc/pms-docker:plexpass
   container_name: plexpass
   volumes:
     - /opt/plex/database:/config
     - /opt/plex/transcode:/transcode
     - /mnt/plexdrive4:/plexdrive4
     - /mnt/unionfs:/unionfs
     - /:/yourcomputer
   ports:
     - 32400:32400
   restart: always
   environment:
     - PUID=1000
     - PGID=1000
