version: "2"
services:
  my-wpdb:
    image: mariadb
    ports:
      - "8081:3306"
    environment:
      MYSQL_ROOT_PASSWORD: SUPERSTrongWp@$$
  my-wp:
    image: wordpress
    volumes:
      - ./:/var/www/html
    ports:
      - "80:80"
    links:
      - my-wpdb:mysql
    environment:
      WORDPRESS_DB_PASSWORD: SUPERSTrongWp@$$
networks:
  default:
    external:
      name: plexguide