defaultEntryPoints = ["http", "https"]

[web]
# Port for the status page
address = ":8080"

# Entrypoints, http and https
[entryPoints]
  # http should be redirected to https
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  # https is the default
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

# Enable ACME (Let's Encrypt): automatic SSL
[acme]
# Email address used for registration
email = "trashbot75@icloud.com"
storageFile = "/opt/appdata/traefik/ssl/acme.json"
entryPoint = "https"
onDemand = false
OnHostRule = true

# Enable Docker configuration backend
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "dunn.cloud"
watch = true
exposedbydefault = false
