#!/bin/bash
#
# [Ansible Role]
#
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   Admin9705 & Deiteq
# URL:      https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
---
- name: Remove couchpotato Container
  docker_container:
    name: couchpotato
    state: absent

- name: Check couchpotato.ini exists
  stat:
    path: "/opt/appdata/couchpotato/config.ini"
  register: cp_ini

- name: Deploy CouchPotato Container
  docker_container:
    name: couchpotato
    image: linuxserver/couchpotato
    pull: yes
    cpu_shares: 256
    published_ports:
      - "{{ports}}5050:5050"
    env:
      APP: couchpotato
      VERSION: stable
      PUID: "1000"
      PGID: "1000"
      VIRTUAL_HOST: "couchpotato.{{domain}}"
      VIRTUAL_PORT: 5050
      HTTPS_METHOD: noredirect
      LETSENCRYPT_HOST: "couchpotato.{{domain}}"
      LETSENCRYPT_EMAIL: "{{email}}"
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:couchpotato.{{domain}}"
      traefik.port: "5050"
    networks:
      - name: plexguide
        aliases:
          - CouchPotato
    volumes:
      - /opt/appdata/couchpotato:/config
      - /mnt/unionfs/completed:/unionfs-downloads:shared
      - /mnt/unionfs:/unionfs
      - /mnt/unionfs/movies:/movies
      - /mnt/sab/complete:/complete
      - /mnt/nzbget/completed:/completed
      - /mnt/deluge/downloaded:/downloaded
      - /mnt/torrentvpn/downloaded:/data/completed
      - /etc/localtime:/etc/localtime:ro
    restart_policy: always
    state: started

- name: Path for .ini
  wait_for:
    path: "/opt/appdata/couchpotato/config.ini"
    state: present
  when: cp_ini.stat.exists == False

- name: "Wait 10 Seconds"
  wait_for:
    timeout: 10
  when: cp_ini.stat.exists == False

- name: Turn the Wizard Off
  replace:
    path: /opt/appdata/couchpotato/config.ini
    regexp: "show_wizard = 1"
    replace: "show_wizard = 0"
  when: cp_ini.stat.exists == False

- name: Turn on Dark Theme
  replace:
    path: /opt/appdata/couchpotato/config.ini
    regexp: "dark_theme = False"
    replace: "dark_theme = True"
  when: cp_ini.stat.exists == False

#- name: Turn On Renamer
  #replace:
    #path: /opt/appdata/couchpotato/config.ini
    #regexp: "enabled = False"
    #replace: "enabled = True"
    #after: "[renamer]"
    #before: "[subtitle]"
  #when: cp_ini.stat.exists == False

- name: Turn off Blackhole
  replace:
    path: /opt/appdata/couchpotato/config.ini
    regexp: "enabled = True"
    replace: "enabled = 0"
    after: "[blackhole]"
  when: cp_ini.stat.exists == False

- name: "Wait 5 Seconds"
  wait_for:
    timeout: 5
  when: cp_ini.stat.exists == False

- name: Stopping CouchPotato Container
  docker_container:
    name: couchpotato
    state: stopped
  when: cp_ini.stat.exists == False

- name: Restarting CouchPotato Container
  docker_container:
    name: couchpotato
    state: started
  when: cp_ini.stat.exists == False
