---
- name: Remove couchpotato Container
  docker_container:
    name: couchpotato
    state: absent

- name: Check sabnzbd.ini exists
  stat:
    path: "/opt/appdata/couchpotato/config.ini"
  register: cp_ini

- name: Deploy CouchPotato Container
  docker_container:
    name: couchpotato
    image: linuxserver/couchpotato
    pull: yes
    cpu_shares: 256
    published_ports:
      - "5050:5050"
    env:
      APP: couchpotato
      VERSION: stable
      PUID: "1000"
      PGID: "1000"
      VIRTUAL_HOST: "couchpotato.{{domain}}"
      VIRTUAL_PORT: 5050
      HTTPS_METHOD: noredirect
      LETSENCRYPT_HOST: "couchpotato.{{domain}}"
      LETSENCRYPT_EMAIL: "{{email}}"
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:couchpotato.{{domain}}"
      traefik.port: "5050"
    networks:
      - name: plexguide
        aliases:
          - CouchPotato
    volumes:
      - /opt/appdata/couchpotato:/config
      - /mnt/unionfs/completed:/unionfs-downloads:shared
      - /mnt/unionfs:/unionfs
      - /mnt/unionfs/movies:/movies
      - /mnt/sab/complete:/complete
      - /mnt/nzbget/completed:/completed
      - /mnt/deluge/downloaded:/downloaded
      - /etc/localtime:/etc/localtime:ro
    restart_policy: always
    state: started

- name: Path for .ini
  wait_for:
    path: "/opt/appdata/couchpotato/config.ini"
    state: present
  when: cp_ini.stat.exists == False

- name: "Wait 10 Seconds"
  wait_for:
    timeout: 10
  when: cp_ini.stat.exists == False

- name: Turn the Wizard Off
  replace:
    path: /opt/appdata/couchpotato/config.ini
    regexp: "show_wizard = 1"
    replace: "show_wizard = 0"
  when: cp_ini.stat.exists == False

- name: Turn on Dark Theme
  replace:
    path: /opt/appdata/couchpotato/config.ini
    regexp: "dark_theme = False"
    replace: "dark_theme = True"
  when: cp_ini.stat.exists == False

- name: Turn off blackhole
  replace:
    path: /opt/appdata/couchpotato/config.ini
    regexp: "enabled = 1"
    replace: "enabled = 0"
    after: "[blackhole]"
    before: "directory = /root"
  when: cp_ini.stat.exists == False

- name: "Wait 5 Seconds"
  wait_for:
    timeout: 5
  when: cp_ini.stat.exists == False

- name: Stopping CouchPotato Container
  docker_container:
    name: couchpotato
    state: stopped
  when: cp_ini.stat.exists == False

- name: Restarting CouchPotato Container
  docker_container:
    name: couchpotato
    state: started
  when: cp_ini.stat.exists == False