---

- name: Remove NZBHyra2 Container
  docker_container:
    name: nzbhydra2
    state: absent

- name: Deploy NZBHyra2 Container
  docker_container:
    name: nzbhydra2
    image: hotio/suitarr
    pull: yes
    cpu_shares: 256
    published_ports:
      - "{{ports}}5076:5076"
    env:
      APP: "nzbhydra2"
      VERSION: "stable"
      PUID: "1000"
      PGID: "1000"
    volumes:
      - "/opt/appdata/nzbhydra2:/config"
      - "/etc/localtime:/etc/localtime:ro"
    restart_policy: always
    networks:
      - name: plexguide
        aliases:
          - nzbhydra2
    state: started
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:nzbhydra2.{{domain}}"
      traefik.port: "5076"
