#!/bin/bash
#
# Version:  Ansible-1
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   Admin9705 & Deiteq & Bryde ãƒ„
# URL:      https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
############################################################# (KEY START)
---
- name: "Establish Key Variables"
  set_fact:
    intport: "8686"
    extport: "8686"
    pgrole: "{{role_name}}"
    image: "linuxserver/lidarr"

- name: "Key Variables Recall"
  include_role:
    name: "pgmstart"
    tasks_from: "keyvar.yml"
############################################################# (KEY END)
#
############################################################# (BASICS START)

- name: "Create {{pgrole}} script directories"
  file: "path={{item}} state=directory mode=0775 owner=1000 group=1000 recurse=yes"
  with_items:
    - /opt/appdata/{{pgrole}}

############################################################# (BASICS END)
- name: "Set Default Volume - {{pgrole}}"
  set_fact:
    default_volumes:
      - "/opt/appdata/{{pgrole}}:/config{{extra}}"
      - /mnt/unionfs:/unionfs
      - "{{path.stdout}}/sab/complete:/complete"
      - "{{path.stdout}}/nzbget/completed:/completed"
      - "{{path.stdout}}/rutorrents:/downloads"
      - "{{path.stdout}}/deluge/downloaded:/downloaded"
      - "{{path.stdout}}/torrentvpn/downloaded:/data/completed"
      - "{{path.stdout}}/qbittorrent/Downloads:/qbittorrent/Downloads"
      - /etc/localtime:/etc/localtime:ro

- name: "Establish Key Variables - {{pgrole}}"
  set_fact:
    default_env:
      UID: "1000"
      GID: "1000"
      APP: "lidarr"
      VERSION: "stable"
      BACKUP: "no"

- name: "Set Default Labels - {{pgrole}}"
  set_fact:
    default_labels:
      traefik.enable: "true"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:{{pgrole}}.{{domain.stdout}},{{tldset}}"
      traefik.port: "{{intport}}"

######################## Deploy PGMSTART
- include_role:
    name: "pgmstart"
