#!/bin/bash
#
# [Ansible Role]
#
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   Admin9705 & Deiteq
# URL:      https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
---
- include_vars: variables.yml

- include_role:
    name: pgmstart

- pause:
    prompt: "\nType Image # for {{role_name}}\n1- linuxserver/lidarr (Recommended)\n2- hotio/suitarr (Space Saver)"
  register: result
  until: result.user_input > "0" and result.user_input < "3"
  retries: 5
  delay: 1

- name: Set linuxserver/lidarr
  set_fact:
    image: "linuxserver/lidarr"
    extra: ""
  when: result.user_input == "1"

- name: Hotio/Suitarr
  set_fact:
    image: "hotio/suitarr:lidarr"
    extra: "/Lidarr"
  when: result.user_input == "2"

- name: Deploy Lidarr Container
  docker_container:
    name: "{{role_name}}"
    image: "{{image}}"
    pull: yes
    cpu_shares: 256
    published_ports:
      - "{{ports.stdout}}{{extport}}:{{intport}}"
    env:
      APP: "lidarr"
      VERSION: "stable"
      PUID: "1000"
      PGID: "1000"
      BACKUP: "no"
      MONO_TLS_PROVIDER: legacy
    networks:
      - name: plexguide
        aliases:
          - lidarr
    volumes:
      - "/opt/appdata/lidarr:/config{{extra}}"
      - /mnt/unionfs:/unionfs
      - "{{path.stdout}}/sab/complete:/complete"
      - "{{path.stdout}}/nzbget/completed:/completed"
      - "{{path.stdout}}/rutorrents:/downloads"
      - "{{path.stdout}}/deluge/downloaded:/downloaded"
      - "{{path.stdout}}/torrentvpn/downloaded:/data/completed"
      - "{{path.stdout}}/qbittorrent/Downloads:/qbittorrent/Downloads"
      - /etc/localtime:/etc/localtime:ro
    restart_policy: always
    state: started
    labels:
      traefik.enable: "true"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:lidarr.{{domain.stdout}}"
      traefik.port: "{{intport}}"

- include_role:
    name: pgmend
