#!/bin/bash
#
# [Ansible Role]
#
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   Admin9705 & Deiteq
# URL:      https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
---
- script: /opt/plexguide/roles/b-srestore/scripts/solo.sh

- name: Register HD Path
  shell: "cat /var/plexguide/server.hd.path"
  register: path
  ignore_errors: True

- name: "Server ID for Restore"
  shell: "cat /var/plexguide/server.id"
  register: server_id

- name: "Checking if Building List Exists"
  stat:
    path: "{{path.stdout}}/pgops/restore.build"
  register: backlistcheck

- name: "Building List"
  shell: "cat {{path.stdout}}/pgops/restore.build"
  register: backlist
  when: backlistcheck.stat.exists == True

- name: Prompt User for Program
  pause:
    prompt: "\n[Detected Programs]: {{backlist.stdout}}\n\nTYPE the name of a PROGRAM to Restore! (Case Senstive)"
  register: selection

- name: Establishing Final Variable - Switch On
  shell: "echo {{selection.user_input}} > {{path.stdout}}/pgops/program_var"

- script: /opt/plexguide/roles/b-srestore/scripts/soloselect.sh

- name: "Checking if Program is Running"
  stat:
    path: "{{path.stdout}}/pgops/{{selection.user_input}}.running"
  register: running

- name: "Remove Static Path"
  shell: "rm -r {{path.stdout}}/pgops/{{selection.user_input}}}.running"
  when: running.stat.exists == True

- debug: msg="{{selection.user_input}}} running? {{running.stat.exists}}"

- name: "Wait 1 Seconds"
  wait_for:
    timeout: 1

- debug: msg="Temp Message - For {{selection.user_input}} - Server ID {{server_id.stdout}}"

- name: "Checking {{selection.user_input}} location in APPDATA"
  stat:
    path: "/opt/appdata/{{selection.user_input}}"
  register: location

- name: Stopping Docker Container - {{selection.user_input}}
  docker_container:
    name: "{{selection.user_input}}"
    state: stopped
  ignore_errors: True
  when: running.stat.exists == True

- debug: msg="Time Length can be Long or Short! Please Wait!"
  when: location.stat.exists == True

- name: Remove Old {{selection.user_input}} from APPDATA
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/opt/appdata/{{selection.user_input}}"

- name: Create Restore Folder
  file: "path={{item}} state=directory mode=0775 owner=1000 group=1000"
  with_items:
    - "/opt/appdata/{{selection.user_input}}"
  ignore_errors: yes

- name: Unzip Folders
  unarchive:
    src: "{{path.stdout}}/pgops/{{selection.user_input}}}.tar"
    dest: "/opt/appdata/{{selection.user_input}}}"
    keep_newer: no
    owner: 1000
    group: 1000
    mode: 0775

- name: "Restart Docker Container - {{selection.user_input}}"
  docker_container:
    name: "{{selection.user_input}}"
    state: started
  ignore_errors: True
  when: running.stat.exists == True

- name: Remove Leftover Tar from /tmp
  file:
    path: "{{item}}"
    state: absent
  ignore_errors: True
  with_items:
    - "{{path.stdout}}/pgops/{{selection.user_input}}}.tar"
