---
cadvisor_docker_image_name: google/cadvisor
cadvisor_docker_version: latest
cadvisor_docker_pull_images: yes
#cadvisor_docker_user: cadvisor-docker
#cadvisor_docker_log_sensitive: yes
#cadvisor_docker_directory: /srv/cadvisor-docker
cadvisor_docker_expose_port: 8082
