---
  - name: Check service exists
    stat:
      path: "/etc/systemd/system/plexdrive4.service"
    register: plexdrive4

  - name: Stop existing plexdrive service
    systemd: state=stopped name=plexdrive4
    when: plexdrive4.stat.exists
    
  - name: Remove Plexdrive Service
    file:
      state: absent
      path: /etc/systemd/system/plexdrive4.service
      force: yes
    when: plexdrive4.stat.exists

  - name: PlexDrive 4 Install
    get_url:
      url:  https://github.com/dweidenfeld/plexdrive/releases/download/5.0.0/plexdrive-linux-amd64
      dest: /tmp
      mode: 0755
      owner: 1000
      group: 1000
      force: yes

  - name: Move PlexDrive4 Service
    template:
      src: plexdrive4.js2
      dest: /etc/systemd/system/plexdrive4.service 
      force: yes
    when: plexdrive4.stat.exists == False

  - name: Daemon-Reload
    systemd: state=stopped name=plexdrive4 daemon_reload=yes enabled=no

  - name: Config Check
    stat:
      path: "/root/.plexdrive/config.json"
    register: plexdrive4

  - name: Start PlexDrive
    systemd: state=started name=plexdrive4 enabled=yes
    when: plexdrive4.stat.exists
    
  - name: Config Present?
    stat:
      path: "/root/.plexdrive/config.json"
    register: plexdrive4_config

  - name: PlexDrive4 Start
    systemd: state=started name=plexdrive4 enabled=yes
    when: plexdrive4_config.stat.exists