---
- name: Warning!
  pause:
    prompt: "[Press Enter to Continue] Note: You are utilizing the STABLE image."

- name: Stop and remove any existing container
  docker_container:
    name: plex
    state: absent

- name: "Get Server IP"
  shell: "hostname -I | awk '{print $1}'"
  register: local_ip

- name: Check Preferences.xml exists
  stat:
    path: "/opt/appdata/plex/Library/Application Support/Plex Media Server/Preferences.xml"
  register: plex_prefs

- debug: msg="Your IP Address is {{local_ip.stdout}}"
  when: plex_prefs.stat.exists == False

- name: Get Plex Media Server claim token
  pause:
    prompt: "Visit http://plex.tv/claim, Copy to Clipboard, and Paste (Press Enter If Already Setup)"
  register: pms_token
  when: plex_prefs.stat.exists == False

- debug: msg="Using following Plex claim token {{pms_token.user_input}}"
  when: plex_prefs.stat.exists == False

- name: Remove Plex Container
  docker_container:
    name: plex
    state: absent

- name: Pull Plex Image
  docker_image:
    name: "plexinc/pms-docker:plexpass"

- name: Deploy Plex Container
  docker_container:
    name: plex
    image: "plexinc/pms-docker:plexpass"
    pull: yes
    published_ports:
      - "32400:32400"
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
      - "33400:33400/tcp"
      - "33443:33443/tcp"
    env:
      PLEX_UID: 1000
      PLEX_GID: 1000
      CHANGE_CONFIG_DIR_OWNERSHIP: false
      PLEX_CLAIM: "{{pms_token.user_input}}"
      ADVERTISE_IP: "{{local_ip.stdout}}:32400/"
      HTTPS_METHOD: noredirect
    etc_hosts: {'metrics.plex.tv': '127.0.0.1', 'analytics.plex.tv': '127.0.0.1'}
    networks:
      - name: plexguide
        aliases:
          - plex
    #network_mode: "host"
    expose:
      - 32400
    volumes:
      - "/tmp:/tmp"
      - "/opt/appdata/plex/database:/config"
      - "/opt/appdata/plex/transcode:/transcode"
      - "/mnt/plexdrive4:/plexdrive4"
      - "/mnt/encrypt:/encrypt"
      - "/mnt/unionfs:/unionfs"
      - "/:/yourcomputer"
      - "/etc/localtime:/etc/localtime:ro"
    cpu_shares: 1024
    restart_policy: always
    state: started
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:plex.{{domain}}"
      traefik.port: "32400"

- name: Create Basic Directories
  file: "path={{item}} state=directory mode=0775 owner=1000 group=1000"
  with_items:
      - /opt/appdata/plex/database/Library/Application Support/Plex Media Server/Plug-ins

## Source: https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server/wiki/Plex-Guide
#### http://docs.ansible.com/ansible/latest/unarchive_module.html
- name: WebTools
  unarchive:
    src: https://github.com/ukdtom/WebTools.bundle/releases/download/3.0.0/WebTools.bundle.zip
    dest: /opt/appdata/plex/database/Library/Application Support/Plex Media Server/Plug-ins
    keep_newer: no
    owner: 1000
    group: 1000
    mode: 0775
    copy: no
