## Notes: https://wiki.archlinux.org/index.php/CPU_frequency_scaling
#!/bin/bash
#
# [Cloudbox Ansible Role]
#
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   13uddz & Desmonic
# URL:      https://cloudbox.rocks
#
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
# Further Enhancements & Options By: PlexGuide.com
#################################################################################

- name: Install CPUFrequtils
  apt: "name={{item}} state=latest"
  with_items:
    - cpufrequtils

########### Remove Governer Policy If Exists

- name: Removing File Directories
  file:
    state: absent
    path: /etc/default/cpufrequtils

########### Set Governer File

- name: CPUFrequtils Checker
  stat:
    path: /etc/default/cpufrequtils
  register: cpu

- name: Create /etc/default/cpufrequtils
  file:
    path: /etc/default/cpufrequtils
    state: touch
  when: cpu.stat.exists == False

########### Establish CPU Performance
## Three Modes With Menu Selection
## 1. Performance, 2. Ondemand, 3. Conservative

- name: CPU Performance = Performance
  lineinfile:
    path: "/etc/default/cpufrequtils"
    regexp: '^GOVENOR\s?='
    line: 'GOVENOR="conservative"'
    state: present

- name: CPU Freq Set
  lineinfile:
    path: "/etc/default/cpufrequtils"
    regexp: '^GOVERNOR\s?='
    line: 'GOVERNOR="conservative"'
    state: present

- name: Enable Governer
  lineinfile:
    path: "/etc/default/cpufrequtils"
    regexp: '^ENABLE\s?='
    line: 'ENABLE="true"'
    state: present

################### STOP SCALING

- name: Disable Scaling Frequency
  shell: "update-rc.d ondemand disable"
