#!/bin/bash
#
# [PlexGuide Ansible Role]
#
# By:  Admin9705 & Deiteq
# URL: https://plexguide.com
#
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
# https://gist.github.com/rbq/886587980894e98b23d0eee2a1d84933
#################################################################################

---
- name: Install list of packages
  apt:
    name: "{{ item }}"
    state: installed
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - docker-ce
  tags: docker_standard

- name: Add Docker GPG key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: Release docker-ce from hold
  dpkg_selections:
    name: docker-ce
    selection: install
  tags: docker_standard
############################################# DEPLOY DOCKER

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

- name: Install docker-ce (Please Wait)
  apt:
    name: docker-ce={{docversion.stdout}}
    state: present
    update_cache: yes
    force: yes
  tags: docker_standard

- name: Put docker-ce into hold
  dpkg_selections:
    name: docker-ce
    selection: hold
  tags: docker_standard

- name: Start docker (Please Wait)
  systemd: state=started name=docker enabled=yes
  tags: docker_standard

- name: create plexguide network
  docker_network:
    name: "plexguide"
    state: present
  tags: docker_standard
