#!/bin/bash
#
# [Ansible Role]
#
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   Admin9705 & Deiteq & FlickerRate
# URL:      https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
---
- include_role:
    name: variables
    
- name: Remove Rutorrent Container
  docker_container:
    name: rutorrent
    state: absent

- name: Deploy Rutorrent Container
  docker_container:
    name: rutorrent
    image: horjulf/rutorrent-autodl
    pull: yes
    cpu_shares: 256
    published_ports:
      - "{{ports.stdout}}8999:80"
      - "51413:51413"
      - "6881:6881/udp"
      - "5000:5000"
    env:
      PUID: "1000"
      PGID: "1000"
    volumes:
      - /opt/appdata/rutorrent/:/config
      - "{{path.stdout}}/rutorrents/:/downloads"
      - /etc/localtime:/etc/localtime:ro
      - /mnt/unionfs/:/unionfs
      - /opt/scripts/torrent:/scripts
    restart_policy: always
    networks:
      - name: plexguide
        aliases:
          - rutorrent
    state: started
    labels:
      traefik.enable: "true"
      traefik.frontend.auth.basic: "{{auth.stdout}}"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:rutorrent.{{domain.stdout}}"
      traefik.port: "80"


###################################### REGEX Source: Desmonic @ CLOUDBOX.rocks

  - name: Check rtorrent.rc exists
  stat:
    path: "/opt/appdata/rutorrent/rtorrent/rtorrent.rc"
  register: rtorrent_rc

- name: Wait for rtorrent.rc to be created
  wait_for:
    path: "/opt/appdata/rutorrent/rtorrent/rtorrent.rc"
    state: present
  when: rtorrent_rc.stat.exists == False

- name: Wait for php.ini to be created
  wait_for:
    path: "/opt/appdata/rutorrent/php/php.ini"
    state: present
  when: rtorrent_rc.stat.exists == False

- name: "Wait for 8 seconds before stopping rutorrent container"
  wait_for:
    timeout: 8
  when: rtorrent_rc.stat.exists == False

- name: Stop container to customize rtorrent.rc
  docker_container:
    name: rutorrent
    image: horjulf/rutorrent-autodl
    state: stopped
  when: rtorrent_rc.stat.exists == False

- name: Change downloads directory
  lineinfile:
    path: "/opt/appdata/rutorrent/rtorrent/rtorrent.rc"
    regexp: '^directory\s?='
    line: 'directory = /{{path.stdout}}/rutorrent'
    state: present
  when: rtorrent_rc.stat.exists == False

- name: Disable DHT
  lineinfile:
    path: "/opt/appdata/rutorrent/rtorrent/rtorrent.rc"
    regexp: '^dht\s?='
    line: 'dht = disable'
    state: present
  when: rtorrent_rc.stat.exists == False

- name: Disable PEX
  lineinfile:
    path: "/opt/appdata/rutorrent/rtorrent/rtorrent.rc"
    regexp: '^peer_exchange\s?='
    line: 'peer_exchange = no'
    state: present
  when: rtorrent_rc.stat.exists == False

- name: Reduce min_peers
  lineinfile:
    path: "/opt/appdata/rutorrent/rtorrent/rtorrent.rc"
    regexp: '^min_peers\s?='
    line: 'min_peers = 1'
    state: present
  when: rtorrent_rc.stat.exists == False

- name: Increase max_uploads
  lineinfile:
    path: "/opt/appdata/rutorrent/rtorrent/rtorrent.rc"
    regexp: '^max_uploads\s?='
    line: 'max_uploads = 1024'
    state: present
  when: rtorrent_rc.stat.exists == False

- name: Disable check_hash
  lineinfile:
    path: "/opt/appdata/rutorrent/rtorrent/rtorrent.rc"
    regexp: '^check_hash\s?='
    line: 'check_hash = no'
    state: present
  when: rtorrent_rc.stat.exists == False

- name: Set upload_rate to unlimited
  lineinfile:
    path: "/opt/appdata/rutorrent/rtorrent/rtorrent.rc"
    regexp: '^upload_rate\s?='
    line: 'upload_rate = 0'
    state: present
  when: rtorrent_rc.stat.exists == False

- name: Set download_rate to unlimited
  lineinfile:
    path: "/opt/appdata/rutorrent/rtorrent/rtorrent.rc"
    regexp: '^download_rate\s?='
    line: 'download_rate = 0'
    state: present
  when: rtorrent_rc.stat.exists == False

- name: Set global upload_rate to unlimited
  lineinfile:
    path: "/opt/appdata/rutorrent/rtorrent/rtorrent.rc"
    regexp: '^throttle.global_up.max_rate.set_kb\s?='
    line: 'throttle.global_up.max_rate.set_kb = 0'
    state: present
  when: rtorrent_rc.stat.exists == False

- name: Set global download_rate to unlimited
  lineinfile:
    path: "/opt/appdata/rutorrent/rtorrent/rtorrent.rc"
    regexp: '^throttle.global_down.max_rate.set_kb\s?='
    line: 'throttle.global_down.max_rate.set_kb = 0'
    state: present
  when: rtorrent_rc.stat.exists == False

- name: Set max_open_files to 1024
  lineinfile:
    path: "/opt/appdata/rutorrent/rtorrent/rtorrent.rc"
    regexp: '^network.max_open_files.set\s?='
    line: 'network.max_open_files.set = 1024'
    state: present
  when: rtorrent_rc.stat.exists == False

- name: Set encryption parameters
  lineinfile:
    path: "/opt/appdata/rutorrent/rtorrent/rtorrent.rc"
    regexp: '^encryption\s?='
    line: 'encryption = allow_incoming,enable_retry,prefer_plaintext'
    state: present
  when: rtorrent_rc.stat.exists == False

- name: Set max_downloads_global to 1024
  lineinfile:
    path: "/opt/appdata/rutorrent/rtorrent/rtorrent.rc"
    regexp: '^max_downloads_global\s?='
    line: 'max_downloads_global = 1024'
    state: present
  when: rtorrent_rc.stat.exists == False

- name: Set max_uploads_global to 1024
  lineinfile:
    path: "/opt/appdata/rutorrent/rtorrent/rtorrent.rc"
    regexp: '^max_uploads_global\s?='
    line: 'max_uploads_global = 1024'
    state: present
  when: rtorrent_rc.stat.exists == False

- name: Set file_allocate to no
  lineinfile:
    path: "/opt/appdata/rutorrent/rtorrent/rtorrent.rc"
    regexp: '^system.file_allocate.set\s?='
    line: 'system.file_allocate.set = no'
    state: present
  when: rtorrent_rc.stat.exists == False

- name: Set upload_max_filesize to 8M
  lineinfile:
    path: "/opt/appdata/rutorrent/php/php.ini"
    regexp: '^upload_max_filesize\s?='
    line: 'upload_max_filesize = 8M'
    state: present
  when: rtorrent_rc.stat.exists == False

- name: Start container to apply changes
  docker_container:
    name: rutorrent
    state: started
  when: rtorrent_rc.stat.exists == False
