---

- name: Remove Rutorrent Container
  docker_container:
    name: rutorrent
    state: absent

- name: Deploy Rutorrent Container
  docker_container:
    name: rutorrent
    image: linuxserver/rutorrent
    pull: yes
    cpu_shares: 256
    published_ports:
      - "8999:80"
      - "51413:51413"
      - "6881:6881/udp"
      - "5000:5000"
    env:
      PUID: "1000"
      PGID: "1000"
      VIRTUAL_HOST: "rutorrent.{{domain}}"
      VIRTUAL_PORT: 8999
      LETSENCRYPT_HOST: "rutorrent.{{domain}}"
      LETSENCRYPT_EMAIL: "{{email}}"
      HTTPS_METHOD: noredirect
    volumes:
      - /opt/appdata/rutorrent/:/config
      - /mnt/rutorrents/downloads/incoming:/downloads
      - /etc/localtime:/etc/localtime:ro
      - /mnt/unionfs/:/unionfs
    restart_policy: always
    networks:
      - name: plexguide
        aliases:
          - rutorrent
    state: started
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:rutorrent.{{domain}}"
      traefik.port: "80"
