---
- name: Remove Wordpress Container
  docker_container:
    name: wordpress
    state: absent

- name: Remove Database Container
  docker_container:
    name: my-wpdb
    state: absent

- name: Deploy Wordpress Database
  docker_container:
    name: my-wpdb
    image: mariadb
    pull: yes
    cpu_shares: 512
    published_ports:
      - "8082:3306"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    env:
      MYSQL_ROOT_PASSWORD: "{{pw}}"
    networks:
      - name: plexguide
        aliases:
          - mariadbwordpress
    restart_policy: always
    state: started

- name: Deploy Wordpress Container
  docker_container:
    name: wordpress
    image: wordpress
    pull: yes
    cpu_shares: 512
    published_ports:
      - "10000:80"
    env:
      APP: wordpress
      PUID: "1000"
      PGID: "1000"
      VIRTUAL_HOST: "{{domain}}"
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: "{{domain}}"
      LETSENCRYPT_EMAIL: "{{email}}"
      WORDPRESS_DB_PASSWORD: "{{pw}}"
    networks:
      - name: plexguide
        aliases:
          - Wordpress
    links:
      - my-wpdb:mysql
    volumes:
      - /opt/appdata/wordpress:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    restart_policy: always
    state: started
