#!/bin/bash
#
# [Ansible Role]
#
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   Admin9705
# URL:      https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
---
- include_role:
    name: variables
##########

- name: Register WP Port
  shell: "cat /var/plexguide/wpport.id"
  register: wpport

- name: Register WP ID
  shell: "cat /var/plexguide/wp.id"
  register: wpid

########## Unique for TLD
- name: Register TLD Checker
  shell: "cat /var/plexguide/wp.tld"
  register: tldcheck
  ignore_errors: True

- name: Comparison Check
  shell: "a=$(cat /var/plexguide/wp.tld); b=$(cat /var/plexguide/wp.id); if [ $a == $b ] ; then echo "yes" 1>/tmp/wp.answer ; else echo "no" 1>/tmp/wp.answer ; fi"
  ignore_errors: True

- name: Register Status
  shell: "cat /tmp/wp.answer"
  register: tldanswer
  ignore_errors: True

- name: Register TLD if it exists
  shell: "cat /var/plexguide/wp.tld"
  ignore_errors: True
  when: tldanswer == "yes"

- name: Register TLD if it does not exist
  shell: "echo ''"
  ignore_errors: True
  when: tldanswer == "no"

- debug: msg="TLD Check - for WPID {{wpid.stdout}} | TLD Check {{tldcheck.stdout}}"
  ignore_errors: True

################# END

- name: Remove Wordpress Container
  docker_container:
    name: "wordpress-{{wpid.stdout}}"
    state: absent

- name: Remove Database Container
  docker_container:
    name: "wordpress-{{wpid.stdout}}-db"
    state: absent

- name: Deploy Wordpress Database
  docker_container:
    name: "wordpress-{{wpid.stdout}}-db"
    image: mariadb
    pull: yes
    cpu_shares: 512
    published_ports:
      - "127.0.0.1:10{{wpport.stdout}}:3306"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/appdata/wordpress/{{wpid.stdout}}-db:/var/lib/mysql"
    env:
      MYSQL_ROOT_PASSWORD: "mYsupERbigPas2WorD"
    networks:
      - name: plexguide
        aliases:
          - "wordpress-{{wpid.stdout}}-db"
    restart_policy: always
    state: started

- name: Deploy Wordpress Container
  docker_container:
    name: wordpress-{{wpid.stdout}}
    image: wordpress
    pull: yes
    cpu_shares: 256
    published_ports:
      - "9{{wpport.stdout}}:80"
    env:
      APP: wordpress
      PUID: "1000"
      PGID: "1000"
      WORDPRESS_DB_PASSWORD: "mYsupERbigPas2WorD"
    networks:
      - name: plexguide
        aliases:
          - "wordpress-{{wpid.stdout}}"
    links:
      - "wordpress-{{wpid.stdout}}-db:mysql"
    volumes:
      - /opt/appdata/wordpress/{{wpid.stdout}}:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    restart_policy: always
    state: started
    labels:
      traefik.enable: "true"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:{{wpid.stdout}}.{{domain.stdout}}{{tldcheck.stdout}}"
      traefik.port: "80"

##### STORE INFO
- name: Store WP Port
  shell: "echo '{{wpport.stdout}}' > /opt/appdata/wordpress/{{wpid.stdout}}/pgwpport"

- name: Store WP ID/Subdomain
  shell: "echo '{{wpid.stdout}}' > /opt/appdata/wordpress/{{wpid.stdout}}/pgsub"

##### OutPut Info
- debug: msg="Database Deployed Internal via Port 10{{wpport.stdout}}"

- debug: msg="Access WP Via Port 9{{wpport.stdout}} - SubDomain >>> {{wpid.stdout}}"