#!/bin/bash
#
# [Ansible Role]
#
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   Admin9705 & Deiteq
# URL:      https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
---
- name: Backup & Restore
  pause:
    prompt: "\nWelcome to the PG Backup & Restore!
\n\n1.  Exit Backup & Restore
\n2.  Change Current  ID: server01
\n3.  Change Recovery ID: server01
\n4.  Backup : Solo Program
\n5.  Backup : Mass Backup
\n6.  Restore: Solo Program
\n7.  Restore: Mass Program
\n\nType a Number Choice"
  register: choice
  until: choice.user_input == "1" or
         choice.user_input == "2" or
         choice.user_input == "3" or
         choice.user_input == "4" or
         choice.user_input == "5" or
         choice.user_input == "6" or
         choice.user_input == "7"
  retries: 99
  delay: 1

- name: Set Choice
  set_fact:
    fchoice: "{{choice.user_input}}"

- name: Exiting Interface
  shell: "echo break > /var/plexguide/br.menu"
  when: fchoice == "1"

- name: Backup Solo
  include_role:
    name: b-sbackup
    tasks_from: "main.yml"
  when: fchoice == "4"

- shell: "echo mbackup > /var/plexguide/br.menu"
  when: fchoice == "5"

- name: Restore Solo
  include_role:
    name: b-srestore
    tasks_from: "main.yml"
  when: fchoice == "6"

- shell: "echo mrestore > /var/plexguide/br.menu"
  when: fchoice == "7"
