#!/bin/bash
#
# [Ansible Role]
#
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   Admin9705 & Deiteq & FlickerRate
# URL:      https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
---
- hosts: localhost
  gather_facts: true
  tasks:
    - name: Register E-Mail
      shell: "cat /var/plexguide/server.email"
      register: email

    - name: Register Domain
      shell: "cat /var/plexguide/server.domain"
      register: domain

    - name: Register Provider
      shell: "cat /var/plexguide/traefik.provider"
      register: provider

    - name: Remove Traefik
      docker_container:
        name: traefik
        state: absent

    - name: Removing Prior Traefik.toml
      file:
        state: absent
        path: /opt/appdata/traefik/traefik.toml

    - name: Create Basic Directories
      file: "path={{item}} state=directory mode=0775 owner=1000 group=1000"
      with_items:
        - /opt/appdata/traefik
        - /opt/appdata/traefik/acme

    ########## Move Script if not Present
    - name: Installing Traefik.Toml
      template:
        src: traefik.toml
        dest: /opt/appdata/traefik/traefik.toml
        force: yes
        owner: 1000
        group: 1000

    - name: Check acme.json exists
      stat:
        path: "/opt/appdata/traefik/acme/acme.json"
      register: acme_json

    - name: Installing ACME
      template:
        src: acme.json
        dest: /opt/appdata/traefik/acme/acme.json
        force: yes
        mode: 0600
        owner: 1000
        group: 1000
      when: acme_json.stat.exists == False
