#!/bin/bash
#
# [Ansible Role]
#
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   Admin9705 & Deiteq & FlickerRate
# URL:      https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
---
- hosts: localhost
  gather_facts: true
  tasks:
    - name: Part 1
      shell: "cat /var/plexguide/GCE_PROJECT"
      register: part1

    - name: Part 2
      shell: "cat /var/plexguide/GCE_SERVICE_ACCOUNT_FILE"
      register: part2

    - name: Deploy Traefik - GCLOUD
      docker_container:
        name: traefik
        image: traefik:1.7
        pull: yes
        published_ports:
          - "443:443"
          - "80:80"
        env:
          PUID: 1000
          PGID: 1000
          PROVIDER: gcloud
          GCE_PROJECT: "{{part1.stdout}}"
          GCE_SERVICE_ACCOUNT_FILE: "{{part2.stdout}}"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
          - /etc/localtime:/etc/localtime:ro
          - /opt/appdata/traefik/traefik.toml:/etc/traefik/traefik.toml:ro
          - /opt/appdata/traefik/acme:/etc/traefik/acme
          - "{{part2.stdout}}:{{part2.stdout}}"
        restart_policy: unless-stopped
        state: started
        networks:
          - name: plexguide
            aliases:
              - traefik
