---
########## Remove old existing Traefik config
- name: Removing File Directories
  file:
    state: absent
    path: /opt/appdata/traefik/traefik.toml

########## Create prerequisite Traefik directories
- name: Create Basic Directories
  file: "path={{item}} state=directory mode=0775 owner=1000 group=1000"
  with_items:
    - /opt/appdata/traefik

#- name: create traefik network
#  docker_network:
#    name: "proxy"
#    state: present

########## Check if Traefik config exists and register
- name: Check if Traefik prerequisites exist
  stat:
    path: "/opt/appdata/traefik/traefik.toml"
  register: config

########## Check if Traefik config exists and register
#- name: Check if Traefik log-prerequisites exist
#  stat:
#    path: "/opt/appdata/traefik/log/traefik.log"
#  register: log

########## Copy Traefik config files
- name: Installing Traefik prerequisites
  template:
    src: traefik.toml
    dest: /opt/appdata/traefik/traefik.toml
    force: yes
  when: config.stat.exists == False

########## Create log files
#- name: Creating Traefik log-prerequisites
#  template:
#    src: traefik.log
#    dest: /opt/appdata/traefik/log/traefik.log
#    force: yes
#  when: log.stat.exists == False

########## Check if Traefik SSL config file exists and register
#- name: Check if SSL prerequisites exist
#  stat:
#    path: "/opt/appdata/traefik/ssl/acme.json"
#  register: ssl_config

########## Copy Traefik SSL config file
#- name: Installing SSL prerequisites
#  template:
#    src: acme.json
#    dest: /opt/appdata/traefik/ssl/acme.json
#    force: yes
#  when: ssl_config.stat.exists == False

########## Ask user for e-mail & domain
#- name: domain
#  pause:
#    prompt: "Enter your domain here"
#  register: domain_input

#- name: email
#  pause:
#    prompt: "Enter your e-mail address here (must be valid in order to register SSL)"
#  register: email_input

########## Info-Debug
#- debug: msg="Using following domain {{domain_input.user_input}}"
#- debug: msg="Using following e-mail {{email_input.user_input}}"

########## Replace template domain and email with the user input
#- name: Replace yourdomain.com with user input
#  replace:
#    path: /opt/appdata/traefik/traefik.toml
#    regexp: yourdomain.com
#    replace: "{{domain_input.user_input}}"

#- name: Replace your@email.com with user input
#  replace:
#    path: /opt/appdata/traefik/traefik.toml
#    regexp: your@email.com
#    replace: "{{email_input.user_input}}"

########## Removes old Traefik container
- name: Remove Traefik
  docker_container:
    name: traefik
    state: absent

########## Deploys new Traefik container
- name: Deploy Traefik and Start SSL
  docker_container:
    name: traefik
    image: traefik
    pull: yes
    cpu_shares: 256
    published_ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      #- /opt/appdata/traefik/traefik.toml:/traefik.toml
      #- /opt/appdata/traefik/acme.json:/acme.json
      - /opt/appdata/traefik/traefik.toml:/etc/traefik/traefik.toml:ro
      - /opt/appdata/traefik/acme.json:/etc/traefik/acme/acme.json
    env:
      PUID: "1000"
      PGID: "1000"
    restart_policy: always
    state: started
#  networks:
#    proxy:
#      external: true