#!/bin/bash
#
# Version:  Ansible-1
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   Admin9705 & Deiteq & PhysK
# URL:      https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
############################################################# (KEY START)
---
- name: "Establish Key Variables"
  set_fact:
    intport: "80"
    extport: "80"
    pgrole: "{{role_name}}"
    image: "physk/sonarr-radarr-tracker"

- name: "Key Variables Recall"
  include_role:
    name: "pgmstart"
    tasks_from: "keyvar.yml"
############################################################# (KEY END)
#
############################################################# (BASICS START)

- name: "Create {{pgrole}} script directories"
  file: "path={{item}} state=directory mode=0775 owner=1000 group=1000 recurse=yes"
  with_items:
    - /opt/appdata/{{pgrole}}

- name: "Download Config File from Github"
  get_url:
    url: https://raw.githubusercontent.com/physk/sonarr-radarr-tracker/master/src/config/config.php
    dest: /opt/appdata/{{pgrole}}/config.php
    mode: 0755

- name: "Getting Sonarr API Key"
  shell: cat /opt/appdata/sonarr/config.xml | grep -o -P '(?<=<ApiKey>).*(?=</ApiKey>)'
  register: SONARRAPI

- name: "Getting Radarr API Key"
  shell: cat /opt/appdata/radarr/config.xml | grep -o -P '(?<=<ApiKey>).*(?=</ApiKey>)'
  register: RADARRAPI

- name: "Replacing config value for Domain"
  replace:
    path: /opt/appdata/{{pgrole}}/config.php
    regexp: 'DOMAIN'
    replace: "{{domain.stdout}}"

- name: "Replacing config value for SiteName"
  replace:
    path: /opt/appdata/{{pgrole}}/config.php
    regexp: 'SITENAME'
    replace: "{{domain.stdout}}"

- name: "Replacing config value for Sonarr API"
  replace:
    path: /opt/appdata/{{pgrole}}/config.php
    regexp: 'SONARRAPI'
    replace: "{{SONARRAPI}}"

- name: "Replacing config value for Radarr API"
  replace:
    path: /opt/appdata/{{pgrole}}/config.php
    regexp: 'RADARRAPI'
    replace: "{{RADARRAPI}}"

############################################################# (BASICS END)
- name: "Set Default Volume - {{pgrole}}"
  set_fact:
    default_volumes:
      - /opt/appdata/{{pgrole}}:/var/www/html/config

- name: "Establish Key Variables - {{pgrole}}"
  set_fact:
    default_env:
      UID: "1000"
      GID: "1000"

- name: "Set Default Labels - {{pgrole}}"
  set_fact:
    default_labels:
      traefik.enable: "true"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:tracker.{{domain.stdout}}"
      traefik.port: "{{intport}}"

######################## Deploy PGMSTART
- include_role:
    name: "pgmstart"