#!/bin/bash
#
# [Ansible Role]
#
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   Admin9705 & Deiteq
# URL:      https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Register Ports
      shell: "cat /var/plexguide/server.ports"
      register: info

    - name: Port Result Open
      set_fact:
        ports: "Open"
      when: info.stdout == ""

    - name: Port Result Closed
      set_fact:
        ports: "Closed"
      when: info.stdout == "127.0.0.1:"

    - name: Version
      shell: "cat /var/plexguide/tld.program"
      register: tldprogram

    - name: Version
      shell: "cat /var/plexguide/pg.number"
      register: pgversion

    - name: Edition
      shell: "cat /var/plexguide/pg.edition"
      register: pgedition

    - name: Server ID
      shell: "cat /var/plexguide/server.id"
      register: pgid

    - name: Domain
      shell: "cat /var/plexguide/server.domain"
      register: pgdomain

    - name: Appguard Status
      shell: "cat /var/plexguide/server.ht"
      register: appguard

    - name: Authentication Not Enabled
      set_fact:
        output: "Not Enabled"
      #when: appguard.stdout == "" and wckdfront.stat.exists == False

    - name: AppGuard Enabled
      set_fact:
        output: "APP Guard Enabled"
      when: not appguard.stdout == ""

    - name: Ansible
      shell: "ansible --version | cut -d' ' -f2 | head -n1"
      register: pgansible
      ignore_errors: True

    #- name: Python
    #  shell: "python3 --version | cut -d' ' -f2"
    #  register: pgpython
    #  ignore_errors: True

##### Recall Mounts or HDs
    - name: Register Mounts or HD Action
      shell: "cat /var/plexguide/pg.edition.stored"
      register: info

    - name: Set Mounts
      set_fact:
        mounts: "PG Mounts & Data Transport"
        backups: "Backup & Restore"
      when: not info.stdout == "PG Edition - HD Solo" and not info.stdout == "PG Edition - HD Multi"

    - name: Set Solo HD
      set_fact:
        mounts: "NOTE: SOLO HD - Unable to Setup GDrive or Multiple HDs"
        backups: "NOTE: SOLO HD - Backup & Restore NOT Enabled (No GDrive)"
      when: info.stdout == "PG Edition - HD Solo"

    - name: Set Multi HDs
      set_fact:
        mounts: "Setup & Deploy Multiple Hard-Drives"
        backups: "NOTE: Multi HD - Backup & Restore NOT Enabled (No GDrive)"
      when: info.stdout == "PG Edition - HD Multi"

    - name: PG Main Menu
      pause:
        prompt: "\n-----------------------------------------------------------------------
               \n{{pgedition.stdout}} - {{pgversion.stdout}} | Server ID: {{pgid.stdout}}
               \nDomain: {{pgdomain.stdout}} | Ansible: {{pgansible.stdout}}
               \n-----------------------------------------------------------------------

                  \n1.  EXIT PlexGuide
                  \n2.  {{mounts}}
                  \n3.  Traefik & TLD Deployment   [{{tldprogram.stdout}}]
                  \n4.  Server Port Guard - Ports  [{{ports}}]
                  \n5.  PG Application Guard       [{{output}}]
                  \n6.  Program Suite Installer
                  \n7.  Plex Enhancement Tools
                  \n8.  PG Automations - Deploy Google Feeder Edition 
                  \n9.  VPN Service Installer
                  \n10. System & Network Auditor
                  \n11. {{backups}}
                  \n12. Settings Menu
                  \n13. TroubleShoot - PreInstaller & UnInstaller
                  \n\nType a [NUMBER] Choice & Press [ENTER]"
      register: choice
      until: choice.user_input == "1" or
             choice.user_input == "2" or
             choice.user_input == "3" or
             choice.user_input == "4" or
             choice.user_input == "5" or
             choice.user_input == "6" or
             choice.user_input == "7" or
             choice.user_input == "8" or
             choice.user_input == "9" or
             choice.user_input == "10" or
             choice.user_input == "11" or
             choice.user_input == "12" or
             choice.user_input == "13"
      retries: 99
      delay: 1

    - name: Set Choice
      set_fact:
        fchoice: "{{choice.user_input}}"

    - name: Exiting Interface
      shell: "echo break > /var/plexguide/main.menu"
      when: fchoice == "1"

    - name: Mount System
      shell: "echo mount > /var/plexguide/main.menu"
      when: fchoice == "2"

    - name: Traefik
      shell: "echo traefik > /var/plexguide/main.menu"
      when: fchoice == "3"

    - shell: "echo ports > /var/plexguide/main.menu"
      when: fchoice == "4"

    - shell: "echo auth > /var/plexguide/main.menu"
      when: fchoice == "5"

    - shell: "echo programs > /var/plexguide/main.menu"
      when: fchoice == "6"

    - shell: "echo plextools > /var/plexguide/main.menu"
      when: fchoice == "7"

    - shell: "echo gce > /var/plexguide/main.menu"
      when: fchoice == "8"

    - shell: "echo pgvpn > /var/plexguide/main.menu"
      when: fchoice == "9"

    - shell: "echo auditor > /var/plexguide/main.menu"
      when: fchoice == "10"

    - shell: "echo backup > /var/plexguide/main.menu"
      when: fchoice == "11"

    - shell: "echo settings > /var/plexguide/main.menu"
      when: fchoice == "12"

    - shell: "echo tshoot > /var/plexguide/main.menu"
      when: fchoice == "13"
