#!/bin/bash
#
# [Ansible Role]
#
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   Admin9705 & MBCorps
# URL:      https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
---
- include_vars: variables.yml

- include_role:
    name: pgmstart

- name: Create Directories
  file: "path={{item}} state=directory mode=0775 owner=1000 group=1000 recurse=true"
  with_items:
    - "/opt/appdata/cloudblitz/"
    - "/opt/appdata/plexguide/supertransfer/"

- name: Check config file exists
  stat:
    path: "/opt/appdata/cloudblitz/.cloudcmd.json"
  register: cloud_json

- name: Install configst2.json
  template:
    src: configst2.json
    dest: /opt/appdata/cloudblitz/.cloudcmd.json
    force: yes
  when: cloud_json.stat.exists == False

- name: Deploy cloudblitz Edition
  docker_container:
    name: cloudblitz
    image: coderaiser/cloudcmd
    pull: yes
    cpu_shares: 256
    published_ports:
      - "{{ports.stdout}}{{extport}}:{{intport}}"
    env:
      PUID: "1000"
      PGID: "1000"
    volumes:
      - /:/SERVER
      - /opt/appdata/cloudblitz:/root/
    networks:
      - name: plexguide
        aliases:
          - cloudblitz
    labels:
      traefik.enable: "true"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:cloudblitz.{{domain.stdout}}"
      traefik.port: "{{intport}}"
    restart_policy: always
    state: started

- include_role:
    name: pgmend
