---
##################################### SERVICE - START
  - name: Daemon-Reload
    systemd: state=stopped name=gdrive daemon_reload=yes enabled=no
    ignore_errors: True

  - name: Remove Service
    file:
      state: absent
      path: /etc/systemd/system/gdrive.service
    ignore_errors: True 
##################################### SERVICE - END
#
#
#
##################################### SERVICE - START
  - name: Daemon-Reload
    systemd: state=stopped name=rclone daemon_reload=yes enabled=no
    ignore_errors: True

  - name: Remove Service
    file:
      state: absent
      path: /etc/systemd/system/rclone.service 
    ignore_errors: True 
##################################### SERVICE ### END
#
#
#
##################################### SERVICE - START
  - name: Daemon-Reload
    systemd: state=stopped name=rclone daemon_reload=yes enabled=no
    ignore_errors: True

  - name: Remove RClone Service
    file:
      state: absent
      path: /etc/systemd/system/rclone.service
    ignore_errors: True    
##################################### SERVICE ### END
#
#
#
##################################### SERVICE - START
  - name: Daemon-Reload
    systemd: state=stopped name=rcache daemon_reload=yes enabled=no
    ignore_errors: True

  - name: Remove RClone Service
    file:
      state: absent
      path: /etc/systemd/system/rcache.service
    ignore_errors: True     
##################################### SERVICE ### END
#
#
#
##################################### SERVICE - START
  - name: Daemon-Reload
    systemd: state=stopped name=tcache daemon_reload=yes enabled=no
    ignore_errors: True

  - name: Remove RClone Service
    file:
      state: absent
      path: /etc/systemd/system/tcache.service 
    ignore_errors: True    
##################################### SERVICE ### END
#
#
#
##################################### SERVICE - START
  - name: Daemon-Reload
    systemd: state=stopped name=rclone-en daemon_reload=yes enabled=no
    ignore_errors: True

  - name: Remove RClone Service
    file:
      state: absent
      path: /etc/systemd/system/rclone-en.service 
    ignore_errors: True    
##################################### SERVICE ### END
#
#
#
##################################### SERVICE - START
  - name: Daemon-Reload
    systemd: state=stopped name=rclone-encrypt daemon_reload=yes enabled=no
    ignore_errors: True

  - name: Remove RClone Service
    file:
      state: absent
      path: /etc/systemd/system/rclone-encrypt.service 
    ignore_errors: True    
##################################### SERVICE ### END
#
#
#
##################################### SERVICE - START
  - name: Daemon-Reload
    systemd: state=stopped name=move daemon_reload=yes enabled=no
    ignore_errors: True

  - name: Remove RClone Service
    file:
      state: absent
      path: /etc/systemd/system/move.service 
    ignore_errors: True    
##################################### SERVICE ### END
#
#
#
##################################### SERVICE - START
  - name: Daemon-Reload
    systemd: state=stopped name=move-en daemon_reload=yes enabled=no
    ignore_errors: True

  - name: Remove RClone Service
    file:
      state: absent
      path: /etc/systemd/system/move-en.service 
    ignore_errors: True    
##################################### SERVICE ### END
#
#
#
##################################### SERVICE - START
  - name: Daemon-Reload
    systemd: state=stopped name=unionfs daemon_reload=yes enabled=no
    ignore_errors: True

  - name: Remove RClone Service
    file:
      state: absent
      path: /etc/systemd/system/unionfs.service 
    ignore_errors: True    
##################################### SERVICE ### END
#
#
#
##################################### SERVICE - START
  - name: Daemon-Reload
    systemd: state=stopped name=unionfs-encrypt daemon_reload=yes enabled=no
    ignore_errors: True

  - name: Remove RClone Service
    file:
      state: absent
      path: /etc/systemd/system/unionfs-encrypt.service 
    ignore_errors: True    
##################################### SERVICE ### END
#
#
#
##################################### SERVICE - START
  - name: Daemon-Reload
    systemd: state=stopped name=v2dockerfix daemon_reload=yes enabled=no
    ignore_errors: True

  - name: Remove RClone Service
    file:
      state: absent
      path: /etc/systemd/system/v2dockerfix.service 
    ignore_errors: True    
##################################### SERVICE ### END

########################################## DOCKERFIX ##################
#
#
#
##################################### SERVICE - START
  - name: Daemon-Reload
    systemd: state=stopped name=plexdrive daemon_reload=yes enabled=no
    ignore_errors: True

  - name: Remove RClone Service
    file:
      state: absent
      path: /etc/systemd/system/plexdrive.service 
    ignore_errors: True    
##################################### SERVICE ### END
#
#
#
##################################### SERVICE - START
  - name: Daemon-Reload
    systemd: state=stopped name=cache daemon_reload=yes enabled=no
    ignore_errors: True

  - name: Remove RClone Service
    file:
      state: absent
      path: /etc/systemd/system/cache.service 
    ignore_errors: True    
##################################### SERVICE ### END
