#!/bin/bash
#
# [Ansible Role]
#
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   Admin9705 & Deiteq
# URL:      https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
---

- name: PG Main Menu
  pause:
    prompt: "\nWelcome to PG Plex Enhancement System!
             \nSelect an Option!
\n\n1.  Exit the Menu!
\n2.  Plex WebTools (Automated Deployment)
\n3.  PG Trak       (Addeds Missing Movies/Shows)
\n\nType a [NUMBER] Choice & Press [ENTER]"
  register: choice
  until: choice.user_input == "1" or
         choice.user_input == "2" or
         choice.user_input == "3"
  retries: 99
  delay: 1

- name: Set Choice
  set_fact:
    fchoice: "{{choice.user_input}}"

- name: Exiting Interface
  shell: "echo break > /var/plexguide/transport.menu"
  when: fchoice == "1"

- name: webtools
  shell: "echo webtools > /var/plexguide/transport.menu"
  when: fchoice == "2"

- name: pgtrak
  shell: "echo pgtrak > /var/plexguide/transport.menu"
  when: fchoice == "3"
