#!/bin/bash
#
# [Ansible Role]
#
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   Admin9705 & Deiteq
# URL:      https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
---
- include_vars: variables.yml

- include_role:
    name: pgmstart

- name: Deploy {{role_name}} Container
  docker_container:
    name: "{{role_name}}"
    image: "linuxserver/{{role_name}}"
    pull: yes
    cpu_shares: 256
    published_ports:
      - "{{ports.stdout}}{{extport}}:{{intport}}"
    env:
      PUID: "1000"
      PGID: "1000"
   #   BACKUP: "no"
    #  MONO_TLS_PROVIDER: legacy
      APP: "{{role_name}}"
      VERSION: "stable"
    volumes:
      - "/opt/appdata/{{role_name}}:/config"
      - "/mnt/unionfs:/unionfs"
      - "{{path.stdout}}/torrentvpn/downloaded:/data/completed"
      - "{{path.stdout}}/sab/complete:/complete"
      - "{{path.stdout}}/nzbget/completed:/completed"
      - "{{path.stdout}}/rutorrents:/downloads"
      - "{{path.stdout}}/deluge/downloaded:/downloaded"
      - "{{path.stdout}}/qbittorrent/Downloads:/qbit-downloads"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - name: plexguide
        aliases:
          - "{{role_name}}"
    restart_policy: always
    state: started
    labels:
      traefik.enable: "true"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:{{role_name}}.{{domain.stdout}}"
      traefik.port: "{{intport}}"

- include_role:
    name: pgmend