# https://cloudplatform.googleblog.com/2017/07/TCP-BBR-congestion-control-comes-to-GCP-your-Internet-just-got-faster.html
# https://www.psc.edu/index.php/networking/641-tcp-tune
#
# [PlexGuide TCP Tuning]
#
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   Flicker-Rate
# URL:      https://plexguide.com
#
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
# TCP BBR significantly improves throughput on high latency & bufferfloat heavy networks
# Requires Linux Kernel <= 4.9
#
# Plex users streaming from faraway servers with aysymetric
# internet speeds will see the most improvement
#
# Real-world benchmark shows 260% increase in download speeds on an iperf test
# With servers in East Germany and Midwest USA on gigabit networks
#################################################################################

########### Check If Backup sysctl exists
- name: sysctl Checker
  stat:
    path: /opt/appdata/plexguide/sysctl.conf
  register: sysctl

########### Backup Sysctl Config
- name: Backup Kernel Parameters
  copy:
    src: /etc/sysctl.conf
    dest: /opt/appdata/plexguide/sysctl.conf
  when: sysctl.stat.exists == False

########### Reset Sysctl Config With Backup File
- name: Reseting Kernel Parameters
  copy:
    src: /opt/appdata/plexguide/sysctl.conf
    dest: /etc/sysctl.conf
  when: sysctl.stat.exists == True

########### Adjust kernel params
# enable/disable tweaks with --skip-tags

#################### bbr
- name: Enable TCP BBR Congestion Control
  blockinfile:
    path: /etc/sysctl.conf
    marker: "# TCP BBR"
    block: |
      net.core.default_qdisc=fq
      net.ipv4.tcp_congestion_control=bbr
  tags:
    - bbr

#################### netsec
- name: Network Security Kernel Tweaks
  blockinfile:
    path: /etc/sysctl.conf
    marker: "# GENERAL NETWORK SECURITY"
    block: |
      net.ipv4.tcp_syncookies = 1
      net.ipv4.tcp_syn_retries = 2
      net.ipv4.tcp_synack_retries = 2
      net.ipv4.tcp_max_syn_backlog = 4096
      net.ipv4.ip_forward = 0
      net.ipv4.conf.all.forwarding = 0
      net.ipv4.conf.default.forwarding = 0
      net.ipv6.conf.all.forwarding = 0
      net.ipv6.conf.default.forwarding = 0
      net.ipv4.conf.all.send_redirects = 0
      net.ipv4.conf.default.send_redirects = 0
      net.ipv4.conf.all.accept_source_route = 0
      net.ipv4.conf.default.accept_source_route = 0
      net.ipv6.conf.all.accept_source_route = 0
      net.ipv6.conf.default.accept_source_route = 0
      net.ipv4.conf.all.rp_filter = 1
      net.ipv4.conf.default.rp_filter = 1
      net.ipv4.conf.all.accept_redirects = 0
      net.ipv4.conf.default.accept_redirects = 0
      net.ipv4.conf.all.secure_redirects = 0
      net.ipv4.conf.default.secure_redirects = 0
      net.ipv6.conf.all.accept_redirects = 0
      net.ipv6.conf.default.accept_redirects = 0
      net.ipv4.conf.all.log_martians = 1
      net.ipv4.conf.default.log_martians = 1
      net.ipv4.tcp_fin_timeout = 7
      net.ipv4.tcp_keepalive_time = 300
      net.ipv4.tcp_keepalive_probes = 5
      net.ipv4.tcp_keepalive_intvl = 15
      net.ipv4.conf.all.bootp_relay = 0
      net.ipv4.conf.all.proxy_arp = 0
      net.ipv4.tcp_timestamps = 1
      net.ipv4.icmp_echo_ignore_all = 0
      net.ipv4.icmp_echo_ignore_broadcasts = 1
      net.ipv4.icmp_ignore_bogus_error_responses = 1
      net.ipv4.ip_local_port_range = 16384 65535
      net.ipv4.tcp_rfc1337 = 1
  tags:
    - netsec

#################### net
- name: Network Performance Kernel Tweaks
  blockinfile:
    path: /etc/sysctl.conf
    marker: "# GENERAL NETWORK PERFORMANCE TWEAKS"
    block: |
      net.ipv4.tcp_window_scaling = 1
      net.ipv4.tcp_rmem = 8192 87380 16777216
      net.ipv4.udp_rmem_min = 16384
      net.core.rmem_default = 262144
      net.core.rmem_max = 16777216
      net.ipv4.tcp_wmem = 8192 65536 16777216
      net.ipv4.udp_wmem_min = 16384
      net.core.wmem_default = 262144
      net.core.wmem_max = 16777216
      net.core.somaxconn = 32768
      net.core.netdev_max_backlog = 16384
      net.core.dev_weight = 64
      net.core.optmem_max = 65535
      net.ipv4.tcp_max_tw_buckets = 1440000
      net.ipv4.tcp_tw_recycle = 0
      net.ipv4.tcp_tw_reuse = 1
      net.ipv4.tcp_max_orphans = 16384
      net.ipv4.tcp_orphan_retries = 0
      net.ipv4.ipfrag_high_thresh = 512000
      net.ipv4.ipfrag_low_thresh = 446464
      net.ipv4.tcp_no_metrics_save = 1
      net.ipv4.tcp_moderate_rcvbuf = 1
      net.unix.max_dgram_qlen = 50
      net.ipv4.neigh.default.gc_thresh3 = 2048
      net.ipv4.neigh.default.gc_thresh2 = 1024
      net.ipv4.neigh.default.gc_thresh1 = 32
      net.ipv4.neigh.default.gc_interval = 30
      net.ipv4.neigh.default.proxy_qlen = 96
      net.ipv4.neigh.default.unres_qlen = 6
      net.ipv4.tcp_retries2 = 15
      net.ipv4.tcp_retries1 = 3
      net.ipv4.tcp_slow_start_after_idle = 0
      net.ipv4.tcp_fastopen = 3
      net.ipv4.route.flush = 1
  tags:
    - net

#################### mem
- name: System Memory Management Kernel Tweaks
  blockinfile:
    path: /etc/sysctl.conf
    marker: "# IMPROVE SYSTEM MEMORY MANAGEMENT"
    block: |
      fs.file-max = 209708
      vm.swappiness = 30
      vm.dirty_ratio = 30
      vm.dirty_background_ratio = 5
      vm.mmap_min_addr = 4096
      vm.overcommit_ratio = 50
      vm.overcommit_memory = 0
      kernel.shmmax = 268435456
      kernel.shmall = 268435456
      vm.min_free_kbytes = 65535
  tags:
      - mem

################### Load Kernel Configs

- name: Apply Kernel Settings
  shell: "sysctl -e -p"
