#!/bin/bash
#
# [Ansible Role]
#
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   Admin9705 & Deiteq & FlickerRate
# URL:      https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
---
- include_role:
    name: variables
    
- name: Portainer Container
  docker_container:
    name: portainer
    state: absent

- name: Create portainer directories
  file: "path={{item}} state=directory mode=0775 owner=1000 group=1000"
  with_items:
    - /opt/appdata/portainer

- name: Deploy Portainer Container
  docker_container:
    name: portainer
    image: portainer/portainer
    pull: yes
    cpu_shares: 256
    published_ports:
      - "{{ports.stdout}}9000:9000"
    env:
      PUID: "1000"
      PGID: "1000"
    volumes:
     - /opt/appdata/portainer:/data
     - /var/run/docker.sock:/var/run/docker.sock
     - /opt/appdata/portainer:/data
    networks:
      - name: plexguide
        aliases:
          - portainer
    restart_policy: always
    state: started
### portainer cannot use auth label; pointless anyways due to creating own user/passwd
    labels:
      traefik.enable: "true"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:portainer.{{domain.stdout}}"
      traefik.port: "9000"
