#!/bin/bash
#
# [Ansible Role]
#
# GitHub:     https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Maintainer: Admin9705 & Deiteq
# URL:        https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
---


############# Pull Basic Information
- name: Reregister Project Link
  shell: "cat /var/plexguide/pgfork.project"
  register: projectfinal

- name: Register Version Link
  shell: "cat /var/plexguide/version.project"
  register: versionfinal

############## Start Asking
- pause:
    prompt: "\nWelcome to PGFork!\n\nProject Link: project\nBranch-Release Link: version\n\n1 - Exit PG Fork\n2 - Download Current Project\n3 - Update Project and/or Branch-Release\n\nType a Selection Number"
  register: exit
  until: exit.user_input > "0" and exit.user_input < "4"
  retries: 99
  delay: 1

- fail:
    msg: "User Opted NOT to CONTINUE! Aborting!"
  when: exit.user_input == "1"

############################## REGISTER PROJECT
- pause:
    prompt: "\nExample: https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server\nPlease Update Your Project Link"
  register: project
  when: exit.user_input == "3"

- name: Store Project Link
  shell: "echo '{{project.user_input}}' > /var/plexguide/pgfork.project"
  when: domainanswer.user_input == "3"

- name: Reregister Project Link
  shell: "cat /var/plexguide/pgfork.project"
  register: projectfinal
  when: domainanswer.user_input == "3"

############################## REGISTER BRANCH
- pause:
    prompt: "\nExample: Version-6 / mybranch / rclonefix\nPlease Update Your Branch-Release"
  register: version
  when: exit.user_input == "3"

- name: Store Project Link
  shell: "echo '{{version.user_input}}' > /var/plexguide/version.project"
  when: domainanswer.user_input == "3"

- name: Reregister Project Link
  shell: "cat /var/plexguide/version.project"
  register: versionfinal
  when: domainanswer.user_input == "3"

############################## Asking If they Wanna Update or Exit?
- pause:
    prompt: "\nCurrently Update Your Project or Exit?\n[1] No - Exit\n[2] Yes - Update\n\nType a Selection Number"
  register: next
  until: next.user_input > "0" and next.user_input < "4"
  retries: 99
  delay: 1
  when: domainanswer.user_input == "3"

- fail:
    msg: "User Opted NOT to CONTINUE! Aborting!"
  when: next.user_input == "2" and domainanswer.user_input == "3"

######################## Start Updating
- name: Delete Current PlexGuide Copy
  shell: "rm -r /opt/plexguide"
  ignore_errors: True

- name: Creating the PG Directory
  file: "path={{item}} state=directory mode=0775 owner=1000 group=1000 recurse=yes"
  with_items:
    - /opt/plexguide/

- name: Clone Fork
  git:
    repo: {{projectfinal.stdout}}
    dest: /opt/plexguide
    version: {{versionfinal.stdout}}
    force: yes
