## Notes: https://wiki.archlinux.org/index.php/CPU_frequency_scaling
########### Original Development of this Script Was Created By desimaniac from https://github.com/desimaniac/Cloudbox

- name: Install CPUFrequtils
  apt: "name={{item}} state=latest"
  with_items:
    - cpufrequtils

########### Remove Governer Policy If Exists

- name: Removing File Directories
  file:
    state: absent
    path: /etc/default/cpufrequtils

########### Set Governer File

- name: CPUFrequtils Checker
  stat:
    path: /etc/default/cpufrequtils
  register: cpu

- name: Create /etc/default/cpufrequtils
  file:
    path: /etc/default/cpufrequtils
    state: touch
  when: cpu.stat.exists == False

########### Establish CPU Performance
## Three Modes With Menu Selection
## 1. Performance, 2. Ondemand, 3. Conservative

- name: CPU Performance = Performance
  lineinfile:
    path: "/etc/default/cpufrequtils"
    regexp: '^GOVENOR\s?='
    line: 'GOVENOR="performance"'
    state: present

- name: CPU Freq Set
  lineinfile:
    path: "/etc/default/cpufrequtils"
    regexp: '^GOVERNOR\s?='
    line: 'GOVERNOR="performance"'
    state: present

- name: Enable Governer
  lineinfile:
    path: "/etc/default/cpufrequtils"
    regexp: '^ENABLE\s?='
    line: 'ENABLE="true"'
    state: present

################### STOP SCALING

- name: Disable Scaling Frequency
  shell: "update-rc.d ondemand disable"
