#!/bin/bash
#
# [Ansible Role]
#
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   Admin9705 & Deiteq & FlickerRate
# URL:      https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
---
################# Remove New PlexDrive Regardless

  - name: Check service exists
    stat:
      path: "/etc/systemd/system/plexdrive.service"
    register: plexdrive

  - name: Stop existing plexdrive service
    systemd: state=stopped name=plexdrive
    when: plexdrive.stat.exists

  - name: Remove Plexdrive Service
    file:
      state: absent
      path: /etc/systemd/system/plexdrive.service
      force: yes
    when: plexdrive.stat.exists
 
  - name: Check PD Binary Exist
    stat:
      path: "/usr/bin/plexdrive"
    register: pdb

  - name: Remove PD Binary
    file:
      state: absent
      path: /usr/bin/plexdrive
      force: yes
    when: pdb.stat.exists

################## Start of New PlexDrive 5 Service

  - name: PlexDrive 5 Install (Be Patient)
    get_url:
      url:  https://github.com/dweidenfeld/plexdrive/releases/download/5.0.0/plexdrive-linux-amd64
      dest: /usr/bin/plexdrive
      mode: 0755
      owner: 1000
      group: 1000
      force: yes
    tags:
      - plexd5

  - name: Move PlexDrive Service
    template:
      src: plexdrive.service
      dest: /etc/systemd/system/plexdrive.service 
      force: yes
    tags:
      - plexd5

  #- name: Move PlexDrive Service
    #template:
      #src: pd5temp.js2
      #dest: /etc/systemd/system/pd5temp.service 
      #force: yes
    #tags:
      #- plexd5

  #- name: Reloading
    #systemd: state=stopped name=pd5temp daemon_reload=yes enabled=no
    #tags:
      #- plexd5

###################### Start of New PlexDrive 4 Service

  - name: Execute MongoDB Script
    script: '/opt/plexguide/scripts/plexdrive/mongod.sh'
    tags:
      - plexd4

  - name: PlexDrive 4 Install (Be Patient)
    get_url:
      url:  https://github.com/dweidenfeld/plexdrive/releases/download/4.0.0/plexdrive-linux-amd64
      dest: /usr/bin/plexdrive
      mode: 0755
      owner: 1000
      group: 1000
      force: yes
    tags:
      - plexd4

  - name: Move PlexDrive Service
    template:
      src: plexdrive4.js2
      dest: /etc/systemd/system/plexdrive.service 
      force: yes
    tags:
      - plexd4
#########
  - name: Reloading
    systemd: state=stopped name=plexdrive daemon_reload=yes enabled=no

  - name: Config Check
    stat:
      path: "/root/.plexdrive/config.json"
    register: token

  - name: Start PlexDrive
    systemd: state=started name=plexdrive enabled=yes
    when: token.stat.exists
    
  - name: Config Present?
    stat:
      path: "/root/.plexdrive/config.json"
    register: plexdrive_config

  - name: PlexDrive Start
    systemd: state=started name=plexdrive enabled=yes

  - name: Kill Switch
    shell: echo "false" > /tmp/alive