#!/bin/bash
#
# [Ansible Role]
#
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   Admin9705 & Deiteq & FlickerRate
# URL:      https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
---
- include_vars: variables.yml

- include_role:
    name: pgmstart

- pause:
    prompt: "\nType Image # for {{role_name}}\n1- linuxserver/ombi (Recommended)\n2- lsiodev/ombi-preview (Developer)"
  register: result
  until: result.user_input > "0" and result.user_input < "4"
  retries: 5
  delay: 1

- name: Set linuxserver/ombi
  set_fact: 
    image: "linuxserver/ombi"
  when: result.user_input == "1"

- name: Set lsiodev/ombi-preview
  set_fact: 
    image: "lsiodev/ombi-preview"
  when: result.user_input == "2"

########## Unique for TLD
- name: Register TLD if it exists
  shell: "cat /var/plexguide/tld.{{role_name}}"
  register: tld
  ignore_errors: True
##########

- name: Create Basic Directories
  file: "path={{item}} state=directory mode=0775 owner=1000 group=1000 recurse=true"
  with_items:
    - /opt/appdata/{{role_name}}

- name: Check JSON exists
  stat:
    path: "/opt/appdata/{{role_name}}/appsettings.json"
  register: jsonfile

- name: Download {{role_name}} appsettings.json config file
  get_url:
    url: https://raw.githubusercontent.com/tidusjar/Ombi/master/src/Ombi/appsettings.json
    dest: /opt/appdata/{{role_name}}/appsettings.json
    owner: 1000
    group: 1000
    force: no
  ignore_errors: True
  when: jsonfile.stat.exists == False

- name: Deploy {{role_name}} Container
  docker_container:
    name: "{{role_name}}"
    image: linuxserver/{{role_name}}
    pull: yes
    cpu_shares: 128
    published_ports:
      - "{{ports.stdout}}{{extport}}:{{intport}}"
    env:
      PUID: "1000"
      PGID: "1000"
    volumes:
      - /opt/appdata/{{role_name}}:/config
      - /etc/localtime:/etc/localtime:ro
      - /opt/appdata/{{role_name}}/appsettings.json:/opt/{{role_name}}/appsettings.json
    networks:
      - name: plexguide
        aliases:
          - "{{role_name}}"
    restart_policy: always
    state: started
    labels:
      traefik.enable: "true"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:{{role_name}}.{{domain.stdout}},requests.{{domain.stdout}},request.{{domain.stdout}}{{tld.stdout}}"
      traefik.port: "{{extport}}"
 
- include_role:
    name: pgmend