#!/bin/bash
#
# [Ansible Role]
#
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   Admin9705 & Deiteq & Clownfused
# URL:      https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
---
- include_vars: variables.yml

- include_role:
    name: pgmstart

- name: Create Phlex Folder(s)
  file: "path={{item}} state=directory mode=0775 owner=1000 group=1000"
  with_items:
    - /opt/appdata/{{pgrole}}/config

- name: Download and Extract Latest Cast.bundle to Plex Plug-ins folder
  unarchive:
    src: https://github.com/d8ahazard/Cast.bundle/archive/master.zip
    dest: /opt/appdata/plex/database/Library/Application Support/Plex Media Server/Plug-ins/
    remote_src: yes
    creates: master.zip
    mode: 0775
    owner: 1000
    group: 1000

- name: Rename Cast.bundle Folder and Delete master.zip File
  shell: mv Cast.bundle-master Cast.bundle && rm master.zip
  args:
    chdir: /opt/appdata/plex/database/Library/Application Support/Plex Media Server/Plug-ins/
    creates: Cast.bundle

- name: Remove Phlex Container
  docker_container:
    name: "{{pgrole}}"
    state: absent

- name: Deploy {{pgrole}} Container
  docker_container:
    name: "{{pgrole}}"
    image: "{{image}}"
    pull: yes
    cpu_shares: 256
    published_ports:
      - "{{ports.stdout}}{{extport}}:{{intport}}"
    env:
      PUID: "1000"
      PGID: "1000"
      HTTPPORT: "{{intport}}"
      FASTCGIPORT: "{{castport}}"

    volumes:
      - "/opt/appdata/{{pgrole}}:/config"

    networks:
      - name: plexguide
        aliases:
          - "{{pgrole}}"
    restart_policy: always
    state: started
    labels:
      traefik.enable: "true"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:{{pgrole}}.{{domain.stdout}}"
      traefik.port: "{{intport}}"

- include_role:
    name: pgmend