#!/bin/bash
#
# [Ansible Role]
#
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   Admin9705 & Deiteq & FlickerRate
# URL:      https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
---
############################ Replace Variables
- name: Register Domain

  
  ignore_errors: True

- name: Register Ports
  shell: "cat /var/plexguide/server.ports"
  register: ports
  ignore_errors: True
############################  Replace Variables
- name: Remove Heimdall Container
  docker_container:
    name: heimdall
    state: absent

- name: Deploy Heimdall Container
  docker_container:
    name: heimdall
    image: linuxserver/heimdall
    pull: yes
    cpu_shares: 256
    published_ports:
      - "{{ports.stdout}}1111:80"
    env:
      PUID: "1000"
      PGID: "1000"
    volumes:
      - "/opt/appdata/heimdall:/config"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - name: plexguide
        aliases:
          - heimdall
    restart_policy: always
    state: started
    labels:
      traefik.enable: "true"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:heimdall.{domain.stdout}}"
      traefik.port: "1111"
