#!/bin/bash
#
# [Ansible Role]
#
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   Admin9705 & Deiteq & FlickerRate
# URL:      https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
---
  - name: Check Transfer Service
    stat:
      path: "/etc/systemd/system/transfer.service"
    register: transfer

  - name: Stop If Transfer Service Running (ignore errors)
    systemd:
      state: stopped
      enabled: no
      name: transfer
    when: transfer.stat.exists
    ignore_errors: True

  - name: Check move Service
    stat:
      path: "/etc/systemd/system/move.service"
    register: move

  - name: Stop If Move Service Running (ignore errors)
    systemd:
      state: stopped
      enabled: no
      name: move
    when: move.stat.exists
    ignore_errors: True

  - name: Check move-en Service
    stat:
      path: "/etc/systemd/system/move.service"
    register: move-en

  - name: Stop If Encrypted Move Service Running (ignore errors)
    systemd:
      state: stopped
      enabled: no
      name: move-en
    when: move.stat.exists
    ignore_errors: True


  - name: Install pgblitz Service
    template:
      src: pgblitz.service
      dest: /etc/systemd/system/pgblitz.service
      force: yes

  - name: Install pgblitz Command
    template:
      src: pgblitz
      dest: /bin/pgblitz
      force: yes

  - name: Set Permissions On pgblitz Command
    shell: "sudo chmod +x /bin/pgblitz"

  - name: Enable pgblitz Service
    systemd:
      daemon_reload: yes
      enabled: yes
      state: restarted
      name: pgblitz

  - name: Install ST2Check Script
    template:
      src: st2monitor.sh
      dest: /opt/appdata/plexguide/st2monitor.sh
      force: yes

########ST2 Monitor
  - name: Check ST2 Check Service
    stat:
      path: "/etc/systemd/system/st2check.service"
    register: st2

  - name: Stop If ST2 Monitor Service Running
    systemd: state=stopped name=st2monitor
    when: st2.stat.exists == True

  - name: Install ST2 Monitor Service
    template:
      src: st2monitor.service
      dest: /etc/systemd/system/st2monitor.service
      force: yes
    when: st2.stat.exists == False

  - name: Daemon-Reload
    systemd: state=stopped name=st2monitor daemon_reload=yes enabled=no
    when: st2.stat.exists == False

  - name: Start ST2 Monitor
    systemd: state=started name=st2monitor enabled=yes
