---
- hosts: localhost

  roles:
  - { role: deploy, tags: ['deploy'] }
  - { role: backup, tags: ['backup'] }
  - { role: autodelete, tags: ['autodelete'] }
  - { role: restore, tags: ['restore'] }
  - { role: restoremass, tags: ['restoremass'] }
  - { role: netdata, tags: ['netdata'] }
  - { role: pushover, tags: ['pushover'] }
  - { role: portainer, tags: ['portainer'] }
  - { role: tautulli, tags: ['tautulli'] }
  - { role: nzbget, tags: ['nzbget'] }
  - { role: nzbhydra, tags: ['nzbhydra'] }
  - { role: variables, tags: ['variables'] }
  - { role: nzbhydra2, tags: ['nzbhydra2'] }
  - { role: muximux, tags: ['muximux'] }
  - { role: plexdrive, tags: ['plexdrive'] }
  - { role: sabnzbd, tags: ['sabnzbd'] }
  - { role: transfer, tags: ['transfer'] }
  - { role: supertransfer, tags: ['supertransfer'] }
  - { role: support, tags: ['support'] }
  - { role: folders_solo, tags: ['folders_solo'] }
  - { role: organizr, tags: ['organizr'] }
  - { role: granfana, tags: ['granfana'] }
  - { role: ombi, tags: ['ombi'] }
  - { role: ombi4k, tags: ['ombi4k'] }
  - { role: sickrage, tags: ['sickrage'] }
  - { role: htpcmanager, tags: ['htpcmanager'] }
  - { role: drives, tags: ['drives'] }
  - { role: emby, tags: ['emby'] }
  - { role: next, tags: ['next'] }
  - { role: telly, tags: ['telly'] }
  - { role: sonarr, tags: ['sonarr'] }
  - { role: sonarr4k, tags: ['sonarr4k'] }
  - { role: radarr, tags: ['radarr'] }
  - { role: radarr4k, tags: ['radarr4k'] }
  - { role: lidarr, tags: ['lidarr'] }
  - { role: deluge, tags: ['deluge'] }
  - { role: test, tags: ['test'] }
  - { role: label, tags: ['label'] }
  - { role: resilio, tags: ['resilio'] }
  - { role: rutorrent, tags: ['rutorrent'] }
  - { role: jackett, tags: ['jackett'] }
  - { role: rclone_un, tags: ['rclone_un'] }
  - { role: rclone_en, tags: ['rclone_en'] }
  - { role: lazy, tags: ['lazy'] }
  - { role: unservices, tags: ['unservices'] }
  - { role: unfiles, tags: ['unfiles'] }
  - { role: unprograms, tags: ['unprograms'] }
  - { role: plex, tags: ['plex'] }
  - { role: plex2, tags: ['plex2'] }
  - { role: medusa, tags: ['medusa'] }
  - { role: dockerfix, tags: ['dockerfix'] }
  - { role: watchtower, tags: ['watchtower'] }
  - { role: wordpress, tags: ['wordpress'] }
  - { role: vnc, tags: ['vnc'] }
  - { role: traefik, tags: ['traefik'] }
  - { role: traefik2, tags: ['traefik2'] }
  - { role: mylar, tags: ['mylar'] }
  - { role: ubooquity, tags: ['ubooquity'] }
  - { role: heimdall, tags: ['heimdall'] }
  - { role: couchpotato, tags: ['couchpotato'] }
  - { role: pyload, tags: ['pyload'] }
  - { role: clean, tags: ['clean'] }
  - { role: clean-encrypt, tags: ['clean-encrypt'] }
  - { role: network_tuning, tags: ['network_tuning'] }
  - { role: docker, tags: ['docker'] }
  - { role: preinstall, tags: ['preinstall'] }
  - { role: commands, tags: ['commands'] }
  - { role: folders, tags: ['folders'] }
  - { role: speedtestserver, tags: ['speedtestserver'] }
  - { role: airsonic, tags: ['airsonic'] }
  - { role: booksonic, tags: ['booksonic'] }
  - { role: duplicati, tags: ['duplicati'] }
  - { role: headphones, tags: ['headphones'] }
