---
- hosts: localhost
  vars_files:
    - /opt/appdata/plexguide/var.yml

  roles:
  - { role: preinstall, tags: ['preinstall'] }
  - { role: backup, tags: ['backup'] }
  - { role: folders, tags: ['folders'] }
  - { role: portainer, tags: ['portainer'] }
  - { role: netdata, tags: ['netdata'] }
  - { role: tautulli, tags: ['tautulli'] }
  - { role: nzbget, tags: ['nzbget'] }
  - { role: nzbhydra, tags: ['nzbhydra'] }
  - { role: nzbhydra2, tags: ['nzbhydra2'] }
  - { role: muximux, tags: ['muximux'] }
  - { role: plexdrive, tags: ['plexdrive'] }
  - { role: sabnzbd, tags: ['sabnzbd'] }
  - { role: support, tags: ['support'] }
  - { role: organizr, tags: ['organizr'] }
  - { role: ombi, tags: ['ombi'] }
  - { role: htpcmanager, tags: ['htpcmanager'] }
  - { role: emby, tags: ['emby'] }
  - { role: sonarr, tags: ['sonarr'] }
  - { role: radarr, tags: ['radarr'] }
  - { role: lidarr, tags: ['lidarr'] }
  - { role: deluge, tags: ['deluge'] }
  - { role: lazy, tags: ['lazy'] }
  - { role: label, tags: ['label'] }
  - { role: resilio, tags: ['resilio'] }
  - { role: rutorrent, tags: ['rutorrent'] }
  - { role: jackett, tags: ['jackett'] }
  - { role: rclone_un, tags: ['rclone_un'] }
  - { role: rclone_en, tags: ['rclone_en'] }
  - { role: unservices, tags: ['unservices'] }
  - { role: unfiles, tags: ['unfiles'] }
  - { role: unprograms, tags: ['unprograms'] }
  - { role: plex, tags: ['plex'] }
  - { role: plex-beta, tags: ['plex-beta'] }
  - { role: docker, tags: ['docker'] }
  - { role: nginx, tags: ['nginx'] }
  - { role: medusa, tags: ['medusa'] }
  - { role: dockerfix, tags: ['dockerfix'] }
  - { role: watchtower, tags: ['watchtower'] }
  - { role: var, tags: ['var'] }
  - { role: revokessl, tags: ['revokessl'] }
  - { role: wordpress, tags: ['wordpress'] }
  - { role: vnc, tags: ['vnc'] }
  - { role: ssl, tags: ['ssl'] }
  - { role: traefik, tags: ['traefik'] }
  - { role: mylar, tags: ['mylar'] }
  - { role: ubooquity, tags: ['ubooquity'] }
  - { role: heimdall, tags: ['heimdall'] }
  - { role: couchpotato, tags: ['couchpotato'] }
