---
- hosts: localhost

  roles:
  - { role: lounge, tags: ['lounge'] }
  - { role: deploy, tags: ['deploy'] }
  - { role: pgtrak, tags: ['pgtrak']}
  - { role: backup, tags: ['backup'] }
  - { role: restore, tags: ['restore'] }
  - { role: restoremass, tags: ['restoremass'] }
  - { role: plextest, tags: ['plextest', 'plextest'] }
  - { role: cadvisor, tags: ['cadvisor', 'monitor'] }
  - { role: prometheus, tags: ['prometheus', 'monitor'] }
  - { role: grafana, tags: ['grafana', 'monitor'] }
  - { role: tautulli, tags: ['tautulli'] }
  - { role: bazarr, tags: ['bazarr'] }
  - { role: nzbget, tags: ['nzbget'] }
  - { role: pgdrive, tags: ['pgdrive'] }
  - { role: rutorrent, tags: ['rutorrent'] }
  - { role: nzbhydra2, tags: ['nzbhydra2'] }
  - { role: variables, tags: ['variables'] }
  - { role: muximux, tags: ['muximux'] }
  - { role: pgdrive_en, tags: ['pgdrive_en'] }
  - { role: pgdupes, tags: ['pgdupes'] }
  - { role: plexdrive, tags: ['plexdrive'] }
  - { role: sabnzbd, tags: ['sabnzbd'] }
  - { role: nowshowing, tags: ['nowshowing'] }
  - { role: transfer, tags: ['transfer'] }
  - { role: cloudcmd, tags: ['cloudcmd'] }
  - { role: pgcache, tags: ['pgcache'] }
  - { role: monitorr, tags: ['monitorr'] }
  - { role: deploy2, tags: ['deploy2'] }
  - { role: calibre, tags: ['calibre'] }
  - { role: supertransfer, tags: ['supertransfer'] }
  - { role: supertransfer2, tags: ['supertransfer2'] }
  - { role: support, tags: ['support'] }
  - { role: organizr, tags: ['organizr'] }
  - { role: ombi, tags: ['ombi'] }
  - { role: ombi4k, tags: ['ombi4k'] }
  - { role: sickrage, tags: ['sickrage'] }
  - { role: htpcmanager, tags: ['htpcmanager'] }
  - { role: drives, tags: ['drives'] }
  - { role: emby, tags: ['emby'] }
  - { role: next, tags: ['next'] }
  - { role: telly, tags: ['telly'] }
  - { role: sstvproxy, tags: ['sstvproxy'] }
  - { role: sonarr, tags: ['sonarr'] }
  - { role: sonarr4k, tags: ['sonarr4k'] }
  - { role: radarr, tags: ['radarr'] }
  - { role: remove, tags: ['remove'] }
  - { role: radarr4k, tags: ['radarr4k'] }
  - { role: lidarr, tags: ['lidarr'] }
  - { role: deluge, tags: ['deluge'] }
  - { role: test, tags: ['test'] }
  - { role: resilio, tags: ['resilio'] }
  - { role: rutorrent, tags: ['rutorrent'] }
  - { role: jackett, tags: ['jackett'] }
  - { role: rclone_un, tags: ['rclone_un'] }
  - { role: rclone_en, tags: ['rclone_en'] }
  - { role: lazy, tags: ['lazy'] }
  - { role: unservices, tags: ['unservices'] }
  - { role: unfiles, tags: ['unfiles'] }
  - { role: plex, tags: ['plex'] }
  - { role: plex2, tags: ['plex2'] }
  - { role: medusa, tags: ['medusa'] }
  - { role: vnc, tags: ['vnc'] }
  - { role: traefik, tags: ['traefik'] }
  - { role: traefik2, tags: ['traefik2'] }
  - { role: mylar, tags: ['mylar'] }
  - { role: ubooquity, tags: ['ubooquity'] }
  - { role: heimdall, tags: ['heimdall'] }
  - { role: couchpotato, tags: ['couchpotato'] }
  - { role: pyload, tags: ['pyload'] }
  - { role: network_tuning, tags: ['network_tuning'] }
  - { role: speedtestserver, tags: ['speedtestserver'] }
  - { role: airsonic, tags: ['airsonic'] }
  - { role: booksonic, tags: ['booksonic'] }
  - { role: duplicati, tags: ['duplicati'] }
  - { role: headphones, tags: ['headphones'] }
  - { role: qbittorrent, tags: ['qbittorrent'] }
  - { role: dns-gen, tags: ['dns-gen'] }
  - { role: services_remove, tags: ['services_remove'] }
  - { role: backup, tags: ['backup'] }
  - { role: radarr-test, tags: ['radarr-test'] }
  - { role: qbittorrent-vpn, tags: ['qbittorrent-vpn'] }
  - { role: webtools, tags: ['webtools'] }
  - { role: jdownloader2, tags: ['jdownloader2'] }
  - { role: plexrequests, tags: ['plexrequests'] }
  - { role: clean-encrypt, tags: ['clean-encrypt'] }
  - { role: organizrv2, tags: ['organizrv2'] }
  - { role: x2go, tags: ['x2go'] }