#!/bin/bash
#
# [RClone Role]
#
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   Admin9705 & Deiteq & FlickerRate
# URL:      https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################

########## Disable Other Services

  - name: Stop If RCLONE Service Running
    systemd: state=stopped name=rclone enabled=no
    ignore_errors: yes
    tags:
      - pgdrive_standard_en

  - name: Stop If encache Service Running
    systemd: state=stopped name=encache enabled=no
    ignore_errors: yes
    tags:
      - pgdrive_standard_en

  - name: Stop If PLEXDRIVE Service Running
    systemd: state=stopped name=plexdrive enabled=no
    ignore_errors: yes
    tags:
      - pgdrive_standard_en

  - name: Stop If RCLONE-ENCRYPT Service Running
    systemd: state=stopped name=rclone-encrypt enabled=no
    ignore_errors: yes
    tags:
      - pgdrive_standard_en

  - name: Stop If RCLONE-EN Service Running
    systemd: state=stopped name=rclone-en enabled=no
    ignore_errors: yes
    tags:
      - pgdrive_standard_en

  - name: Stop If MOVE-EN Service Running
    systemd: state=stopped name=move-en enabled=no
    ignore_errors: yes
    tags:
      - pgdrive_standard_en

  - name: Stop If UNIONFS-EN Service Running
    systemd: state=stopped name=unionfs-encrypt enabled=no
    ignore_errors: yes
    tags:
      - pgdrive_standard_en


#  - name: Stop If GDRIVE Service Running
#    systemd: state=stopped name=gdrive enabled=no
#    ignore_errors: yes
#    tags:
#      - pgdrive_standard_en

#  - name: Stop If TDRIVE Service Running
#    systemd: state=stopped name=tdrive enabled=no
#    ignore_errors: yes
#    tags:
#      - pgdrive_standard_en

  - name: SHELL COMMAND 1
    shell: "mkdir -p /root/.config/rclone/"
    ignore_errors: True
    tags:
      - pgdrive_standard_en

  - name: SHELL COMMAND 2
    shell: "chown -R 1000:1000 /root/.config/rclone/"
    ignore_errors: True
    tags:
      - pgdrive_standard_en

  - name: SHELL COMMAND 3
    shell: "chmod 775 /root/.config/rclone/rclone.conf"
    ignore_errors: True
    tags:
      - pgdrive_standard_en

########################################## MOVE START
  - name: Daemon-Reload
    systemd: state=stopped name=supertransfer2 daemon_reload=yes enabled=no
    ignore_errors: True
    tags:
      - move_en

  - name: Install Move Service to /opt/appdata/plexguide
    template:
      src: move_script.js2
      dest: /opt/appdata/plexguide/move.sh
      force: yes
    tags:
      - move_en

#  - name: Stop If Move Service Running
#    systemd: state=stopped name=move
#    tags:
#      - move_en
#    ignore_errors: yes

  - name: Install Move Service
    template:
      src: move.js2
      dest: /etc/systemd/system/move.service
      force: yes
    tags:
      - move_en

#  - name: Daemon-Reload
#    systemd: state=stopped name=move daemon_reload=yes enabled=no
#    tags:
#      - move_en

  - name: Start Move
    systemd: state=started name=move daemon_reload=yes enabled=yes
    tags:
      - move_en
########################################## MOVE END

########### GCRYPT
  - name: Stop If GDRIVE Service Running
    systemd: state=stopped name=gdrive
    tags:
      - gcrypt
    ignore_errors: yes

  - name: Daemon-Reload - Stop GDRIVE Service
    systemd: state=stopped name=gdrive daemon_reload=yes enabled=no
    tags:
      - gcrypt
    ignore_errors: yes

  - name: Stop If GCRYPT Service Running
    systemd: state=stopped name=gcrypt
    tags:
      - gcrypt
    ignore_errors: yes

  - name: Install GCRYPT Service
    template:
      src: gcrypt.js2
      dest: /etc/systemd/system/gcrypt.service
      force: yes
    tags:
      - gcrypt

  - name: Daemon-Reload
    systemd: state=stopped name=gcrypt daemon_reload=yes enabled=no
    tags:
      - gcrypt

  - name: Start GCRYPT
    systemd: state=started name=gcrypt daemon_reload=yes enabled=yes
    tags:
      - gcrypt

########### TCRYPT
#  - name: Stop If TDRIVE Service Running
#    systemd: state=stopped name=tdrive
#    tags:
#      - tcrypt
#    ignore_errors: yes

#  - name: Daemon-Reload - Stop TDRIVE Service
#    systemd: state=stopped name=tdrive daemon_reload=yes enabled=no
#    tags:
#      - tcrypt
#    ignore_errors: yes

#  - name: Stop If TCRYPT Service Running
#    systemd: state=stopped name=tcrypt
#    tags:
#      - tcrypt
#    ignore_errors: yes

  - name: Install TCRYPT Service
    template:
      src: tcrypt.js2
      dest: /etc/systemd/system/tcrypt.service
      force: yes
    tags:
      - tcrypt

#  - name: Daemon-Reload
#    systemd: state=stopped name=tcrypt daemon_reload=yes enabled=no
#    tags:
#      - tcrypt

  - name: Start TCRYPT
    systemd: state=started name=tcrypt daemon_reload=yes enabled=yes
    tags:
      - tcrypt

########### UNIONFS
  - name: Register UNIONFS PATH
    shell: "cat /tmp/path"
    register: unionfs_path
    tags:
      - unionfs_en
    ignore_errors: True

#  - name: Stop If UNIONFS Service Running
#    systemd: state=stopped name=unionfs
#    tags:
#      - unionfs_en
#    ignore_errors: yes

  - name: Install UNIONFS Service
    template:
      src: unionfs.js2
      dest: /etc/systemd/system/unionfs.service
      force: yes
    tags:
      - unionfs_en

#  - name: Daemon-Reload
#    systemd: state=stopped name=unionfs daemon_reload=yes enabled=no
#    tags:
#      - unionfs_en

  - name: Start UNIONFS
    systemd: state=started name=unionfs daemon_reload=yes enabled=yes
    tags:
      - unionfs_en

########Unionfs Monitor
  - name: Stop If UFS Monitor Service Running
    systemd: state=stopped name=ufsmonitor
    ignore_errors: True
    tags:
      - ufsmonitor_en

  - name: Install UFS Monitor Service
    template:
      src: ufsmonitor.service
      dest: /etc/systemd/system/ufsmonitor.service
      force: yes
    ignore_errors: True
    tags:
      - ufsmonitor_en

  - name: Install UFS Script
    template:
      src: ufsmonitor.sh
      dest: /opt/appdata/plexguide/ufsmonitor.sh
      force: yes
    ignore_errors: True
    tags:
      - ufsmonitor_en

  - name: Daemon-Reload
    systemd: state=stopped name=ufsmonitor daemon_reload=yes enabled=no
    ignore_errors: True
    tags:
      - ufsmonitor_en

  - name: Start UFS Monitor
    systemd: state=started name=ufsmonitor enabled=yes
    ignore_errors: True
    tags:
      - ufsmonitor_en
