#!/bin/bash
#
# Version:  Ansible-1
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   Admin9705 & Deiteq & Bryde ãƒ„
# URL:      https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
############################################################# (KEY START)
---
- name: "Establish Key Variables"
  set_fact:
    intport: "3579"
    extport: "3574"
    pgrole: "{{role_name}}"
    image: "linuxserver/ombi"

- name: Key Variables Recall
  include_role:
    name: pgmstart
    tasks_from: "keyvar.yml"
############################################################# (KEY END)
#
############################################################# (BASICS START)
- name: Create Basic Directories
  file: "path={{item}} state=directory mode=0775 owner=1000 group=1000 recurse=true"
  with_items:
    - "/opt/appdata/{{pgrole}}"

- name: Check JSON exists
  stat:
    path: "/opt/appdata/{{pgrole}}/appsettings.json"
  register: jsonfile

- name: "Download {{pgrole}} appsettings.json config file"
  get_url:
    url: https://raw.githubusercontent.com/tidusjar/Ombi/master/src/Ombi/appsettings.json
    dest: /opt/appdata/{{pgrole}}/appsettings.json
    owner: 1000
    group: 1000
    force: no
  ignore_errors: True
  when: jsonfile.stat.exists == False
############################################################# (BASICS END)
- name: "Set Default Volume - {{pgrole}}"
  set_fact:
    default_volumes:
      - "/opt/appdata/{{pgrole}}:/config"
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/appdata/{{pgrole}}/appsettings.json:/opt/{{pgrole}}/appsettings.json"

- name: "Establish Key Variables - {{pgrole}}"
  set_fact:
    default_env:
      PUID: "1000"
      PGID: "1000"

- name: "Set Default Labels - {{pgrole}}"
  set_fact:
    default_labels:
      traefik.enable: "true"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:{{pgrole}}.{{domain.stdout}},{{tldset}},requests.{{domain.stdout}},request.{{domain.stdout}}"
      traefik.port: "{{intport}}"

######################## Deploy PGMSTART
- include_role:
    name: "pgmstart"
