#!/bin/bash
#
# [Cleaner]
#
# Further Enhanced by DesignGears, Admin9705 & Migz: https://plexguide.com
# GitHub: https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
#
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
# You may copy, distribute and modify the software as long as you track
# changes/dates in source files. Any modifications to our software
# including (via compiler) GPL-licensed code must also be made available
# under the GPL along with build & install instructions.
#############
# Credit to ENZTV for the basis of this script https://enztv.wordpress.com/2017/03/09/unionfs-cleanup/
###############################################
---
- name: Install gdriveclean; remove old cronjob
  cron:
    name: "gdriveclean"
    user: "root"
    state: absent
  ignore_errors: yes

- name: Install gdriveclean; insert script
  template:
    src: gdriveclean.js2
    dest: /opt/appdata/plexguide/gdriveclean.sh
    force: yes
  ignore_errors: yes

- name: Install gdriveclean; cronjob
  cron:
    name: "gdriveclean"
    user: "root"
    minute: "*"
    hour: "*"
    job: "bash /opt/appdata/plexguide/gdriveclean.sh"
  ignore_errors: yes