#!/bin/bash
#
# [Ansible Role]
#
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   Admin9705 & Deiteq
# URL:      https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
---
- include_vars: variables.yml

- include_role:
    name: pgmstart
    
- pause:
    prompt: "\nType of Image for Radarr4K\n1- linuxserver/radarr (Recommended)\n2- hotio/suitrr (Space Saver)\n3- aront/radarr (MP4 Converter)"
  register: result
  until: result.user_input > "0" and result.user_input < "4"
  retries: 5
  delay: 1

- name: Set linuxserver/radarr
  set_fact: 
    image: "linuxserver/radarr"
    extra: ""
  when: result.user_input == "1"

- name: Hotio/Suitarr
  set_fact: 
    image: "hotio/suitarr:radarr"
    extra: "/Sonarr"
  when: result.user_input == "2"

- name: Aront/Radarr
  set_fact: 
    image: "aront/radarr"
    extra: ""
  when: result.user_input == "3"

- name: Create Folders
  file: "path={{item}} state=directory mode=0775 owner=1000 group=1000"
  with_items:
    - /opt/appdata/{{role_name}}/mp4_automator

- name: Deploy {{role_name}} Container
  docker_container:
    name: "{{role_name}}"
    image: "{{image}}"
    pull: yes
    cpu_shares: 128
    published_ports:
      - "{{ports.stdout}}{{extport}}:{{intport}}"
    env:
      PUID: "1000"
      PGID: "1000"
      BACKUP: "no"
      MONO_TLS_PROVIDER: legacy
      APP: "radarr"
      VERSION: "stable"
    volumes:
      - /opt/appdata/{{role_name}}/mp4_automator:/config_mp4_automator
      - "/opt/appdata/{{role_name}}{{extra}}:/config"
      - /mnt/unionfs:/unionfs
      - "{{path.stdout}}/torrentvpn/downloaded:/data/completed"
      - "{{path.stdout}}/sab/complete:/complete"
      - "{{path.stdout}}/nzbget/completed:/completed"
      - "{{path.stdout}}/rutorrents:/downloads"
      - "{{path.stdout}}/deluge/downloaded:/downloaded"
      - /mnt/qbittorrent/Downloads:/qbit-downloads
      - /etc/localtime:/etc/localtime:ro
    networks:
      - name: plexguide
        aliases:
          - "{{role_name}}"
    restart_policy: always
    state: started
    labels:
      traefik.enable: "true"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:{{role_name}}.{{domain.stdout}}"
      traefik.port: "{{extport}}"


- name: Install autoProcess.ini
  template:
    src: autoProcess.ini
    dest: /opt/appdata/{{role_name}}/mp4_automator/autoProcess.ini
    force: yes
    mode: 0775
    owner: 1000
    group: 1000

- include_role:
    name: pgmend