---
- name: Remove Old MOTD
  file: "path={{item}} state=absent"
  with_items:
    - /etc/update-motd.d
    - /etc/motd
    - /etc/motd.dynamic

- name: Deploy Dynamic MOTD
  file:
    path: /etc/update-motd.d
    state: directory
    mode: 0775

- name: Import Support Files
  copy: "src={{item}} dest=/etc/update-motd.d/{{item}} force=yes mode=0775"
  with_items:
    - 00-header
    - 10-sysinfo
    - 90-footer

- name: Symlink
  file:
    src: /var/run/motd
    dest: /etc/motd
    state: link
    force: yes

- name: Npm Mods
  npm: "name={{item}} global=yes"
  with_items:
    - frontail