#!/bin/bash
#
# [Ansible Role]
#
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   Admin9705 & Deiteq & Bryde ãƒ„
# URL:      https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
---
- name: Launch Core Task
  include_tasks: "core.yml"

- name: "Deploy {{pgrole}} Container"
  docker_container:
    name: "{{pgrole}}"
    image: "{{image}}"
    pull: yes
    cpu_shares: 256
    env: 
      PROVIDER: "{{provider}}"
      DOMAIN: "{{cookiedomain}}"
      EMAILS: "{{emails}}"
    restart_policy: always
    networks:
      - name: plexguide
        aliases:
          - "{{pgrole}}"
    state: started
    labels: "{{default_labels}}"
  when: question1 is defined and question1 == "1"

- name: Create the file, if it doesnt exist already
  file:
    path: /var/plexguide/authclient.wckd
    state: touch
  when: question1 is defined and question1 == "1"

- name: Remove file
  file:
    path: /var/plexguide/authclient.wckd
    state: absent
  when: question1 is defined and question1 == "2"

- name: "WCKD Auth is enabled"
  pause:
    prompt: "WCKD Auth is enabled, please rebuild the containers manually to activate WCKD Auth. [ENTER]"
  when: question1 is defined and question1 == "1"

- name: "WCKD Auth is disabled"
  pause:
    prompt: "WCKD Auth is disabled, please rebuild the containers manually to deactivate WCKD Auth. [ENTER]"
  when: question1 is defined and question1 == "2"

- include_role:
    name: pgmend
