---
- name: Remove Watchtower Container
  docker_container:
    name: watchtower
    state: absent

- name: Deploy Watchtower
  docker_container:
    name: watchtower
    image: v2tec/watchtower
    pull: yes
    command: medusa tautulli jackett nzbhydra nzbhydra2 nzbget organizr muximux portainer sonarr radarr watchtower ombi traefik --cleanup --interval 600
    cpu_shares: 64
    state: started
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    restart_policy: always
    networks:
      - name: plexguide
        aliases:
          - watchtower
