---

- name: Remove NZBHYDRA Container
  docker_container:
    name: nzbhydra
    state: absent

- name: Deploy NZBHyra Container
  docker_container:
    name: nzbhydra
    image: hotio/suitarr
    pull: yes
    cpu_shares: 256
    published_ports:
      - "{{ports}}5075:5075"
    env:
      APP: "nzbhydra"
      VERSION: "stable"
      PUID: "1000"
      PGID: "1000"
    volumes:
      - "/opt/appdata/nzbhydra:/config"
      - "/etc/localtime:/etc/localtime:ro"
    restart_policy: always
    networks:
      - name: plexguide
        aliases:
          - nzbhydra
    state: started
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:nzbhydra.{{domain}}"
      traefik.port: "5075"
