---

- name: Remove Ombi Container
  docker_container:
    name: ombi
    state: absent

- name: Deploy Ombi Container
  docker_container:
    name: ombi
    image: lsiodev/ombi-preview
    pull: yes
    cpu_shares: 128
    published_ports:
      - "3579:3579"
    env:
      PUID: "1000"
      PGID: "1000"
      VIRTUAL_HOST: "ombi.{{domain}}"
      VIRTUAL_PORT: 3579
      LETSENCRYPT_HOST: "ombi.{{domain}}"
      LETSENCRYPT_EMAIL: "{{email}}""
    volumes:
      - /opt/appdata/ombiv3:/config
      - /etc/localtime:/etc/localtime:ro
    restart_policy: always
    state: started
