---

- name: Remove Tautulli Container
  docker_container:
    name: tautulli
    state: absent

- name: Deploy Tautulli Container
  docker_container:
    name: tautulli
    image: "shiggins8/tautulli"
    pull: yes
    cpu_shares: 256
    published_ports:
      - "8181:8181"
    volumes:
      - /opt/appdata/tautulli:/config
      - /opt/appdata/plex/Library/Application\ Support/Plex\ Media\
    env:
      PUID: "1000"
      PGID: "1000"
      HTTPS_METHOD: noredirect
    restart_policy: always
    networks:
      - name: plexguide
        aliases:
          - tautulli
    state: started
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:plexpy.{{domain}}"
      traefik.frontend.rule2: "Host:tautulli.{{domain}}"
      traefik.port: "8181"
