#!/bin/bash
#
# [Ansible Role]
#
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   Admin9705 & Deiteq & FlickerRate
# URL:      https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
---
############################ VARIABLES START
- name: Register Domain
  shell: "cat /var/plexguide/server.domain"
  register: domain
  ignore_errors: True

- name: Register Ports
  shell: "cat /var/plexguide/server.ports"
  register: domain
  ignore_errors: True
############################ VARIABLES END
- name: Remove Tautulli Container
  docker_container:
    name: tautulli
    state: absent

- name: Deploy Tautulli Container
  docker_container:
    name: tautulli
    image: "shiggins8/tautulli"
    pull: yes
    cpu_shares: 256
    published_ports:
      - "{{ports.stdout}}8181:8181"
    volumes:
      - /opt/appdata/tautulli:/config
      - /opt/appdata/plex/Library/Application\ Support/Plex\ Media\
    env:
      PUID: "1000"
      PGID: "1000"
    restart_policy: always
    networks:
      - name: plexguide
        aliases:
          - tautulli
    state: started
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:tautulli.{{domain.stdout}},plexpy.{{domain.stdout}}"
      traefik.port: "8181"
