---
- name: Remove Lidarr Container
  docker_container:
    name: lidarr
    state: absent

- name: Deploy Lidarr Container
  docker_container:
    name: lidarr
    image: linuxserver/lidarr
    pull: yes
    cpu_shares: 256
    published_ports:
      - "{{ports}}8686:8686"
    env:
      PUID: "1000"
      PGID: "1000"
      HTTPS_METHOD: noredirect
    networks:
      - name: plexguide
        aliases:
          - lidarr
    volumes:
      - /opt/appdata/lidarr:/config
      - /mnt/unionfs:/unionfs
      - /mnt/sab/complete:/complete
      - /mnt/nzbget/completed:/completed
      - /mnt/rutorrents:/downloads
      - /mnt/deluge/downloaded:/downloaded
      - /mnt/torrentvpn/downloaded:/data/completed
      - /etc/localtime:/etc/localtime:ro
    restart_policy: always
    state: started
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:lidarr.{{domain}}"
      traefik.port: "8686"
