#!/bin/bash
#
# [Ansible Role]
#
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   Admin9705 & Deiteq & FlickerRate
# URL:      https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
---
- name: Create Basic Directories
  file: "path={{item}} state=directory mode=0775 owner=1000 group=1000"
  with_items:
      - /opt/appdata/plex/database/Library/Application Support/Plex Media Server/Plug-ins

- debug: msg="Local Plex Server Installed"

- name: WebTools
  unarchive:
    src: https://github.com/ukdtom/WebTools.bundle/releases/download/3.0.0/WebTools.bundle.zip
    dest: /opt/appdata/plex/database/Library/Application Support/Plex Media Server/Plug-ins
    keep_newer: no
    owner: 1000
    group: 1000
    mode: 0775
    copy: no